import type { Sprite } from './ref-pixelart';

// Sprite 16x16 theo mã món. Hiện chưa module nào import; tách khỏi ref-pixelart.ts để bundler loại khỏi bản build
// (các phép gán/Object.assign bên dưới khiến nó không tree-shake được khi nằm chung file với FURNITURE_SPRITES).

export const PRODUCT_SPRITES: Record<string, Sprite> = {
  mi_goi: [
    '................',
    '.kkkkkkkkkkkkkk.',
    'kRrrrrrrrrrrrrRk',
    'krrwrrrrrrrrrrrk',
    'krrrrrrrrrrrrrrk',
    'kyyyyyyyyyyyyyyk',
    'kyoyyoyyoyyoyyyk',
    'kyyoyyoyyoyyoyyk',
    'kyyyyyyyyyyyyyyk',
    'krrrrrrrrrrrrrrk',
    'krrrwwwwwwrrrrrk',
    'krrrrrrrrrrrrrrk',
    'kRrrrrrrrrrrrrRk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  gao: [
    '................',
    '......kkkk......',
    '.....kBbbBk.....',
    '......kcck......',
    '....kkcccckk....',
    '...kccccccccck..',
    '..kccccccccccck.',
    '..kcrrrrrrrrrck.',
    '..kcrwwrwwrwrck.',
    '..kcrrrrrrrrrck.',
    '..kccccccccccck.',
    '..kcccWccWcccck.',
    '..kccccccccccck.',
    '...kccccccccck..',
    '....kkkkkkkk....',
    '................',
  ],
  nuoc_mam: [
    '......kkkk......',
    '......krrk......',
    '......kRRk......',
    '......kwwk......',
    '......kwwk......',
    '.....kweewk.....',
    '....kweeeewk....',
    '....keeeeeek....',
    '....kyyyyyyk....',
    '....kyrrrryk....',
    '....kyrwwryk....',
    '....kyrrrryk....',
    '....kyyyyyyk....',
    '....keeeeeek....',
    '....keeeeeek....',
    '.....kkkkkk.....',
  ],
  dau_an: [
    '.....kkkkk......',
    '.....knnnk......',
    '.....kNNNk......',
    '......kwk.......',
    '.....kwwwk......',
    '....kwyyywk.....',
    '...kwyyyyywk....',
    '...kyyyyyyyk....',
    '...knnnnnnnk....',
    '...knwwwwwnk....',
    '...knnnnnnnk....',
    '...kyyyyyyyk....',
    '...kywyyyyyk....',
    '...kyyyyyyyk....',
    '...kYYYYYYYk....',
    '....kkkkkkk.....',
  ],
  duong: [
    '................',
    '...kkkkkkkkkk...',
    '...kWwwwwwwWk...',
    '...kwwwwwwwwk...',
    '...kLLLLLLLLk...',
    '...kLwwLLwwLk...',
    '...kLLLLLLLLk...',
    '...kwwwwwwwwk...',
    '...kwWWwwWWwk...',
    '...kwWWwwWWwk...',
    '...kwwwwwwwwk...',
    '...kwwwWWwwwk...',
    '...kwwwWWwwwk...',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  muoi: [
    '................',
    '.....kkkkkk.....',
    '....kggggggk....',
    '....kgkggkgk....',
    '....kggggggk....',
    '....kkkkkkkk....',
    '....klwwwwlk....',
    '....klwwwwlk....',
    '....klwWwwlk....',
    '....klwwwwlk....',
    '....klwwWwlk....',
    '....klwwwwlk....',
    '....klWwwwlk....',
    '....klwwwwlk....',
    '....kkkkkkkk....',
    '................',
  ],
  snack: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kRRRRRRRRRRk..',
    '..kooooooooook..',
    '..kowwwwwwwwok..',
    '..kooooooooook..',
    '..koooyyyyoook..',
    '..kooyyyYyyook..',
    '..kooyyYyyyook..',
    '..koooyyyyoook..',
    '..kooooooooook..',
    '..kooooooooook..',
    '..kRRRRRRRRRRk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  keo: [
    '................',
    '................',
    '................',
    '................',
    'kpk...kkkk...kpk',
    'kppk.kppppk.kppk',
    'kpppkpwwpppkpppk',
    'kpppkppppppkpppk',
    'kpppkppppRpkpppk',
    'kppk.kppppk.kppk',
    'kpk...kkkk...kpk',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  banh_quy: [
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkttttttkk...',
    '..kttBtttttttk..',
    '.kttttBtttttttk.',
    '.kttttttttBtttk.',
    '.ktBttttttttttk.',
    '.kttttttBtttttk.',
    '.ktttttttttttBk.',
    '.kttBtttttttttk.',
    '..kttttttBtttk..',
    '...kkttttttkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  que_cay: [
    '................',
    '...kkkkkkkkkk...',
    '...kRRRRRRRRk...',
    '...krrrrrrrrk...',
    '...krrryrrrrk...',
    '...krryyyrrrk...',
    '...kryyoyyrrk...',
    '...kryoooyyrk...',
    '...kryoooyyrk...',
    '...krryyyyrrk...',
    '...krrrrrrrrk...',
    '...krwwwwwwrk...',
    '...krrrrrrrrk...',
    '...kRRRRRRRRk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  xa_phong: [
    '................',
    '..........kk....',
    '.........kwwk...',
    '..........kk....',
    '......kk........',
    '.....kwwk.......',
    '......kk........',
    '..kkkkkkkkkkkk..',
    '.klwwlllllllllk.',
    '.klwllllllllllk.',
    '.kllllLLLLllllk.',
    '.kllllllllllllk.',
    '.kLLLLLLLLLLLLk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  kem_danh_rang: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkk...',
    '.kwwwwwwwwwwwkkk',
    'kwwLLLLLLLwwwkrk',
    'kwLwwwwwwLwwwkrk',
    'kwwLLLLLLLwwwkrk',
    '.kwwwwwwwwwwwkkk',
    '..kkkkkkkkkkk...',
    '................',
    '................',
    '................',
    '................',
  ],
  giay_vs: [
    '................',
    '................',
    '....kkkkkkkk....',
    '...kWWWWWWWWk...',
    '...kWWWkkWWWk...',
    '...kwWWWWWWwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '....kkkkkkkk....',
    '................',
  ],
  pin: [
    '................',
    '......kkkk......',
    '......kYYk......',
    '....kkkkkkkk....',
    '....kyyyyyyk....',
    '....knnnnnnk....',
    '....knnwnnnk....',
    '....knwwwnnk....',
    '....knnwnnnk....',
    '....knnnnnnk....',
    '....knnnnnnk....',
    '....kNNNNNNk....',
    '....knnnnnnk....',
    '....kggggggk....',
    '....kkkkkkkk....',
    '................',
  ],
  nuoc_ngot: [
    '................',
    '.....kkkkkk.....',
    '....kWggggWk....',
    '....kkkkkkkk....',
    '....krrrrrrk....',
    '....krwrrrrk....',
    '....krwrrrrk....',
    '....kwwwwwwk....',
    '....krrrrrrk....',
    '....krrwwrrk....',
    '....krrrrrrk....',
    '....krrrrrrk....',
    '....kRrrrrRk....',
    '....kkkkkkkk....',
    '....kWggggWk....',
    '.....kkkkkk.....',
  ],
  nuoc_suoi: [
    '......kkkk......',
    '......kLLk......',
    '......kkkk......',
    '.....klllwk.....',
    '....klllllwk....',
    '....kllllllk....',
    '....kLLLLLLk....',
    '....kwwwwwwk....',
    '....kwLLLLwk....',
    '....kwwwwwwk....',
    '....kllllllk....',
    '....kllllllk....',
    '....kllllllk....',
    '....kllllllk....',
    '.....kkkkkk.....',
    '................',
  ],
  tra_xanh: [
    '......kkkk......',
    '......kwwk......',
    '......kkkk......',
    '.....knnnnk.....',
    '....knnnnnnk....',
    '....kyyyyyyk....',
    '....kyyyyyyk....',
    '....knnnnnnk....',
    '....knwwwwnk....',
    '....knwNNwnk....',
    '....knwwwwnk....',
    '....knnnnnnk....',
    '....kyyyyyyk....',
    '....kyyyyyyk....',
    '.....kkkkkk.....',
    '................',
  ],
  tang_luc: [
    '................',
    '.....kkkkkk.....',
    '....kWggggWk....',
    '....kkkkkkkk....',
    '....kLLLLLLk....',
    '....kLLLyLLk....',
    '....kLLyyLLk....',
    '....kLyyyyLk....',
    '....kLLLyyLk....',
    '....kLLLyLLk....',
    '....kLLyLLLk....',
    '....kLLLLLLk....',
    '....kLLLLLLk....',
    '....kkkkkkkk....',
    '....kWggggWk....',
    '.....kkkkkk.....',
  ],
  sua_hop: [
    '................',
    '........kk......',
    '.......kWk......',
    '...kkkkkWkkkk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kLLLLLLLLk...',
    '...kLwwLLLLLk...',
    '...kLwwLLLLLk...',
    '...kLLLLLLLLk...',
    '...kwwwwwwwwk...',
    '...kwllwwllwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  trung_ga: [
    '................',
    '................',
    '................',
    '.....kkk........',
    '....kcccck......',
    '...kccwcccck....',
    '...kcwcccccck...',
    '..kcccccccccck..',
    '..kcccccccccck..',
    '..kccccccccctk..',
    '..kcccccccccttk.',
    '...kcccccccttk..',
    '...kcccccctttk..',
    '....kktttttkk...',
    '......kkkkk.....',
    '................',
  ],
  banh_mi: [
    '................',
    '................',
    '................',
    '..........kkk...',
    '........kktttk..',
    '......kkttttyk..',
    '....kkttytttk...',
    '...kttttttytk...',
    '..kttytttttk....',
    '..kttttytttk....',
    '.kttttttttk.....',
    '.kyttttyttk.....',
    '.kteeeeeek......',
    '..kkkkkkk.......',
    '................',
    '................',
  ],
  rau_muong: [
    '................',
    '..k....k....k...',
    '.knk..knk..knk..',
    '.knnk.knk.knnk..',
    '..knk.knk.knk...',
    '..knnkknkknnk...',
    '...knknnnknk....',
    '....knnnnnk.....',
    '....kNnnnNk.....',
    '.....kNnNk......',
    '.....kNnNk......',
    '....kyyyyyk.....',
    '....kNnnNNk.....',
    '.....kNnNk......',
    '.....kNNNk......',
    '......kkk.......',
  ],
  sua_tuoi: [
    '................',
    '......kkkk......',
    '.....kwwwwk.....',
    '.....kkkkkk.....',
    '....kwwwwwwk....',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kLLLLLLLLk...',
    '...kLwLLLLwLk...',
    '...kLLwwwwLLk...',
    '...kLLLLLLLLk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '....kkkkkkkk....',
    '................',
  ],
  dau_hu: [
    '................',
    '................',
    '................',
    '................',
    '....kkkkkkkk....',
    '...kccccccccck..',
    '..kcccccccccck..',
    '..kkkkkkkkkkck..',
    '..kcccccccckck..',
    '..kcccwcccckck..',
    '..kcccccccckck..',
    '..kccccccccckk..',
    '..kcccccccccck..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  kem_que: [
    '................',
    '.....kkkkk......',
    '....kpppppk.....',
    '...kppwppppk....',
    '...kpwppppk.....',
    '...kpppppppk....',
    '...kppppppk.....',
    '...kpppppppk....',
    '...kppppppk.....',
    '....kpppppk.....',
    '.....kkkkk......',
    '.......kbk......',
    '.......kbk......',
    '.......kbk......',
    '.......kkk......',
    '................',
  ],
  kem_hop: [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kpppppppppppk.',
    '..kkkkkkkkkkkkk.',
    '..kwwwwwwwwwwwk.',
    '..kwppwwwwLLwwk.',
    '..kwppwwwwLLwwk.',
    '..kwwwwyywwwwwk.',
    '..kwwwwyywwwwwk.',
    '..kwwwwwwwwwwwk.',
    '..kLLLLLLLLLLLk.',
    '..kLLLLLLLLLLLk.',
    '...kkkkkkkkkkk..',
    '................',
    '................',
  ],
  xuc_xich: [
    '................',
    '................',
    '................',
    '............kk..',
    '..........kkRk..',
    '........kkrrRk..',
    '......kkrrrrk...',
    '.....krrwrrk....',
    '....krrwrrk.....',
    '...krrrrrk......',
    '..krrrrRk.......',
    '..kRrrRk........',
    '..kkRkk.........',
    '...kk...........',
    '................',
    '................',
  ],
  ha_cao: [
    '................',
    '................',
    '................',
    '................',
    '......kkkk......',
    '....kkccwcck....',
    '...kcccwccwck...',
    '..kcwccccwcck...',
    '..kcccccccccck..',
    '..kcccccccccck..',
    '..kttcccccccttk.',
    '...kttttttttk...',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  cha_gio: [
    '................',
    '................',
    '................',
    '...........kk...',
    '.........kkyYk..',
    '.......kkyyyYk..',
    '.....kkyyYyyk...',
    '....kyyyyyyk....',
    '...kyYyyyyk.....',
    '..kyyyyYyk......',
    '..kYyyyyk.......',
    '..kYYyyk........',
    '...kkkk.........',
    '................',
    '................',
    '................',
  ],
  nuoc_da: [
    '................',
    '.......kk.......',
    '......kWWk......',
    '.....kkkkkk.....',
    '....kllllllk....',
    '...kllwlllllk...',
    '...klwllwlllk...',
    '...kllllllwlk...',
    '...klwlllllllk..',
    '...kllllwlllk...',
    '...klllllllwk...',
    '...kllwllllllk..',
    '...klllllllllk..',
    '....kllllllllk..',
    '.....kkkkkkkk...',
    '................',
  ],
};

// Hàng sau quầy có sprite riêng để phân biệt rõ khi xếp ở quầy nhỏ.
PRODUCT_SPRITES.the_cao = [
  '................', '....kkkkkkkk....', '...kLLLLLLLLk...', '..kLwwwwwwwwLk..',
  '.kLwwwwwwwwwwLk.', '.kLwwwwwwwwwwLk.', '.kLwwLLLLwwwwLk.', '.kLwwLLLLwwwwLk.',
  '.kLwwwwwwwwwwLk.', '.kLwwwwwwwwwwLk.', '..kLwwwwwwwwLk..', '...kLLLLLLLLk...',
  '....kkkkkkkk....', '................', '................', '................',
];
PRODUCT_SPRITES.gas_mini = [
  '................', '.......kk.......', '......kYYk......', '......kYYk......',
  '.....kkrrkk.....', '....krrrrrrk....', '...krrrrrrrrk...', '...krrwwrrrrk...',
  '...krrrrrrrrk...', '...krrrrrrrrk...', '...krrrrrrrrk...', '...krrrrrrrrk...',
  '....krrrrrrk....', '.....kkkkkk.....', '................', '................',
];
PRODUCT_SPRITES.bat_lua = [
  '................', '..........kYY...', '.........kYyYk..', '..........kYY...',
  '......kkkkkk....', '.....kYYYYYYk...', '.....kYwwwwwYk..', '.....kYwyywYk...',
  '.....kYwwwwwYk..', '.....kYYYYYYk...', '.....kNNNNNNk...', '.....kNnnnnNk...',
  '.....kNnnnnNk...', '......kkkkkk....', '................', '................',
];
// Phase 4 product art: reuse matching item silhouettes until bespoke sprites are drawn.
for (const [id, source] of Object.entries({
  banh_tet: 'banh_mi', hat_dua: 'snack', bao_li_xi: 'keo', banh_trung_thu: 'banh_quy', long_den: 'bat_lua',
  tap_vo: 'gao', but_bi: 'bat_lua', ao_mua: 'sua_tuoi', xuc_xich_nuong_tp: 'xuc_xich', mi_ly_tp: 'mi_goi',
  banh_mi_trung_tp: 'banh_mi', trung_luoc_tp: 'trung_ga', tra_tac_tp: 'tra_xanh', ca_phe_sua_tp: 'nuoc_ngot',
  nuoc_mia_tp: 'nuoc_ngot', sinh_to_tp: 'sua_hop', tra_sua_tp: 'sua_hop', tra_tac_base: 'tra_xanh',
  ca_phe_bot: 'nuoc_ngot', mia: 'banh_mi', trai_cay: 'rau_muong',
})) PRODUCT_SPRITES[id] = PRODUCT_SPRITES[source];

// Hàng tạp hóa bổ sung: sprite riêng cho từng món.
Object.assign(PRODUCT_SPRITES, {
  bot_canh: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kYyYyYyYyYyk..',
    '..kyyyyyyyyyyk..',
    '..kyynnnnnnyyk..',
    '..kynwwwwwwnyk..',
    '..kynwrrrrwnyk..',
    '..kynwwwwwwnyk..',
    '..kyynnnnnnyyk..',
    '..kyyyyyyyyyyk..',
    '..kywwyyyyyyyk..',
    '..kyyyyyyyyyyk..',
    '..kYyYyYyYyYyk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  bot_ngot: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kLlLlLlLlLlk..',
    '..kwwwwwwwwwwk..',
    '..kwWwwwWwwWwk..',
    '..kwwwWwwwWwwk..',
    '..kLLLLLLLLLLk..',
    '..kLrrrrrrrrLk..',
    '..kLrwwwwwwrLk..',
    '..kLrrrrrrrrLk..',
    '..kLLLLLLLLLLk..',
    '..kwWwwWwwwWwk..',
    '..kLlLlLlLlLlk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  hat_nem: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kRrRrRrRrRrk..',
    '..kooooooooook..',
    '..kowwwwwwwwok..',
    '..kwwyYyyYywwk..',
    '..kwyyyYYyyywk..',
    '..kwwyyyyyywwk..',
    '..kowwwwwwwwok..',
    '..korrrrrrrrok..',
    '..korwwwwwwrok..',
    '..korrrrrrrrok..',
    '..kRrRrRrRrRrk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  nuoc_tuong: [
    '......kkkk......',
    '......krrk......',
    '......kRRk......',
    '......kBBk......',
    '......kBBk......',
    '.....kBBBBk.....',
    '....kBBBBBBk....',
    '....kBwBBBBk....',
    '....kwwwwwwk....',
    '....kwnnnnwk....',
    '....kwnwwnwk....',
    '....kwnnnnwk....',
    '....kwwwwwwk....',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '.....kkkkkk.....',
  ],
  tuong_ot: [
    '.......kk.......',
    '......knnk......',
    '......kNNk......',
    '.....kkkkkk.....',
    '.....krrrrk.....',
    '....krrrrrrk....',
    '....krwrrrrk....',
    '....krwrrrrk....',
    '....kwwwwwwk....',
    '....kwwwnwwk....',
    '....kwwrrwwk....',
    '....kwwrrwwk....',
    '....kwwwrwwk....',
    '....kRRRRRRk....',
    '....kRRRRRRk....',
    '.....kkkkkk.....',
  ],
  hu_tieu_goi: [
    '................',
    '.kkkkkkkkkkkkkk.',
    'kLlLlLlLlLlLlLlk',
    'kllllllllllllllk',
    'klwwwwwwwwwwwwlk',
    'klwcwcwcwcwcwwlk',
    'klwwcwcwcwcwcwlk',
    'klwcwcwcwcwcwwlk',
    'klwwwwwwwwwwwwlk',
    'kllllllllllllllk',
    'kllrrrrrrllnnllk',
    'kllllllllllllllk',
    'kLlLlLlLlLlLlLlk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  chao_goi: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kNnNnNnNnNnk..',
    '..knnnnnnnnnnk..',
    '..knwwwwwwwwnk..',
    '..knwwWwwWwwnk..',
    '..knkkkkkkkknk..',
    '..knkccccccknk..',
    '..knkcttcctknk..',
    '..knnkccccknnk..',
    '..knnnkkkknnnk..',
    '..knnyyyyyynnk..',
    '..kNnNnNnNnNnk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  sua_dac: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kssssssssssk..',
    '..kSSSSSSSSSSk..',
    '..kLLLLLLLLLLk..',
    '..kLwLLLLLLLLk..',
    '..kLLwwwwwwLLk..',
    '..kLwwccccwwLk..',
    '..kLwcyyyycwLk..',
    '..kLLwwwwwwLLk..',
    '..kLLLLLLLLLLk..',
    '..kSSSSSSSSSSk..',
    '..kssssssssssk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  ca_hop: [
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    'kssssssssssssssk',
    'kSSSSSSSSSSSSSSk',
    'krrrrrrrrrrrrrrk',
    'krwwwwwwwwwwwwrk',
    'krwwLLLLLwwwLwrk',
    'krwLLwLLLLwLLwrk',
    'krwwLLLLLwwwLwrk',
    'krwwwwwwwwwwwwrk',
    'krrrrrrrrrrrrrrk',
    'kSSSSSSSSSSSSSSk',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  pate_hop: [
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kssssssssssk..',
    '..kSSSSSSSSSSk..',
    '..kyyyyyyyyyyk..',
    '..kybbbbbbbbyk..',
    '..kybppppppbyk..',
    '..kybpkppkpbyk..',
    '..kybbbbbbbbyk..',
    '..kyyyyyyyyyyk..',
    '..kSSSSSSSSSSk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  tieu_xay: [
    '................',
    '.....kkkkkk.....',
    '....krwrrrrk....',
    '....kRRRRRRk....',
    '....kkkkkkkk....',
    '....kwdgddgk....',
    '....kdgddgdk....',
    '....kwwwwwwk....',
    '....kwrrrrwk....',
    '....kwwwwwwk....',
    '....kddgdgdk....',
    '....kgddgddk....',
    '....kdgdddgk....',
    '....kddgddgk....',
    '.....kkkkkk.....',
    '................',
  ],
  mam_tom: [
    '................',
    '....kkkkkkkk....',
    '....kyyyyyyk....',
    '....kYYYYYYk....',
    '...kkkkkkkkkk...',
    '...kvwvvvvvvk...',
    '...kvvvvvvvvk...',
    '...kwwwwwwwwk...',
    '...kwwooowwwk...',
    '...kwowwwowwk...',
    '...kwwwwoowwk...',
    '...kwwwwwwwwk...',
    '...kvvvvvvvvk...',
    '...kvvvvvvvvk...',
    '...kVVVVVVVVk...',
    '....kkkkkkkk....',
  ],
  ca_phe_hoa_tan: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kBBBBBBBBBBk..',
    '..kBrrrrrrrrBk..',
    '..kBBBBBBBBBBk..',
    '..kBBBwBBwBBBk..',
    '..kBBwBBwBBBBk..',
    '..kBkkkkkkBBBk..',
    '..kBkeeeekkBBk..',
    '..kBkwwwwkBkBk..',
    '..kBkwwwwkkBBk..',
    '..kBBkwwkBBBBk..',
    '..kBkkkkkkBBBk..',
    '..kBBBBBBBBBBk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  bot_chien: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kYyYyYyYyYyk..',
    '..kyyyyyyyyyyk..',
    '..kyrrrrrrrryk..',
    '..kyrwwwwwwryk..',
    '..kyrrrrrrrryk..',
    '..kyyyyyyyyyyk..',
    '..kyyooooyyyyk..',
    '..kyootoooyyyk..',
    '..kyyoooooooyk..',
    '..kyyyyyyyoRyk..',
    '..kYyYyYyYyYyk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  dau_hao: [
    '......kkkk......',
    '......krrk......',
    '.....kkkkkk.....',
    '.....kBBBBk.....',
    '....kBBBBBBk....',
    '...kBwBBBBBBk...',
    '...kBBBBBBBBk...',
    '...krrrrrrrrk...',
    '...krwwwwwwrk...',
    '...krwssswwrk...',
    '...krwwwwwwrk...',
    '...krrrrrrrrk...',
    '...kBBBBBBBBk...',
    '...kBBBBBBBBk...',
    '....kkkkkkkk....',
    '................',
  ],
  bun_kho: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kppppppppppk..',
    '..kwwwwwwwwwwk..',
    '..kwcwcwcwcwwk..',
    '..kwwcwcwcwcwk..',
    '..kwcwcwcwcwwk..',
    '..kppppppppppk..',
    '..kpwwwwwwwwpk..',
    '..kppppppppppk..',
    '..kwcwcwcwcwwk..',
    '..kwwcwcwcwcwk..',
    '..kppppppppppk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  giam: [
    '.......kk.......',
    '......kLLk......',
    '......kkkk......',
    '......kiik......',
    '......kiik......',
    '.....kiiiik.....',
    '....kiwiiiik....',
    '....kiiiiiik....',
    '....knnnnnnk....',
    '....knwwwwnk....',
    '....knnnnnnk....',
    '....kiiiiiik....',
    '....kiiiiiik....',
    '....kiiiiiik....',
    '....kiiiiiik....',
    '.....kkkkkk.....',
  ],
  keo_cao_su: [
    '................',
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    'kLllllllllllllLk',
    'kllwlllllllllllk',
    'kwwwwwwwwwwwwwwk',
    'kwppwppwppwppwwk',
    'kwwwwwwwwwwwwwwk',
    'kllllllllllllllk',
    'kLllllllllllllLk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  banh_gao: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kLlLlLlLlLlk..',
    '..kllllllllllk..',
    '..klwwwwwwwwlk..',
    '..klwwttttwwlk..',
    '..klwtYttYtwlk..',
    '..klwttttttwlk..',
    '..klwtYttYtwlk..',
    '..klwwttttwwlk..',
    '..klwwwwwwwwlk..',
    '..kllrrrrrrllk..',
    '..kLlLlLlLlLlk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  banh_bong_lan: [
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    'kwwwwwwwwwwwwwwk',
    'kwBBBBBBBBBBBBwk',
    'kwbbbbbbbbbbbbwk',
    'kwyyyyyyyyyyyywk',
    'kwyyYyyyyyYyyywk',
    'kwyyyyyyYyyyyywk',
    'kwyyyyyyyyyyyywk',
    'kwccccccccccccwk',
    'kwwwwwwwwwwwwwwk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  banh_socola: [
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    'krrrrrrrrrrrrrrk',
    'krwwrrrrrrrrrrrk',
    'krrrrrkkkkrrrrrk',
    'krrrkkBBBBkkrrrk',
    'krrkBBBBBBBBkrrk',
    'krrkbbbbbbbbkrrk',
    'krrkwwwwwwwwkrrk',
    'krrkBBBBBBBBkrrk',
    'krrrkkBBBBkkrrrk',
    'krrrrrkkkkrrrrrk',
    'krrrrrrrrrrrrrrk',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  dau_phong: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kRrRrRrRrRrk..',
    '..kwwwwwwwwwwk..',
    '..kwttwwwttwwk..',
    '..kwteewtteewk..',
    '..kwwttwwwttwk..',
    '..kwwwwttwwwwk..',
    '..krrrrrrrrrrk..',
    '..krwwwwwwwwrk..',
    '..krrrrrrrrrrk..',
    '..kwttwwwwttwk..',
    '..kRrRrRrRrRrk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  rong_bien: [
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    'kNNNNNNNNNNNNNNk',
    'kNwNNNNNNNNNNNNk',
    'kNNkkkkkkkkkkNNk',
    'kNNkddnddddnkNNk',
    'kNNkddddddddkNNk',
    'kNNkdnddddndkNNk',
    'kNNkddddddddkNNk',
    'kNNkkkkkkkkkkNNk',
    'kNNNNNNNNNNNNNNk',
    'knnyyyyyyyynnnnk',
    'kNNNNNNNNNNNNNNk',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  kho_ga: [
    '................',
    '....kkkkkkkk....',
    '....krrrrrrk....',
    '....kRRRRRRk....',
    '...kkkkkkkkkk...',
    '...kwoeoonook...',
    '...kwoonoeook...',
    '...kyyyyyyyyk...',
    '...kyrrrrrryk...',
    '...kyyyyyyyyk...',
    '...kwoeoonook...',
    '...kwooeoonok...',
    '...kwnooeoook...',
    '...kwoooooeok...',
    '...kkkkkkkkkk...',
    '................',
  ],
  khan_giay: [
    '................',
    '................',
    '......kkkk......',
    '.....kwwwwk.....',
    '......kwwk......',
    '.kkkkkkwwkkkkkk.',
    '.klllllwwlllllk.',
    '.kllllkkkkllllk.',
    '.kllllllllllllk.',
    '.klpllllllllplk.',
    '.kllllllllllllk.',
    '.kllllpllpllllk.',
    '.kLLLLLLLLLLLLk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  ban_chai: [
    '................',
    '..kkkkk.........',
    '..kwwwk..kkkkk..',
    '..kwlwk..kwwwk..',
    '..kwwwk..kwpwk..',
    '..kwlwk..kwwwk..',
    '..kLLLk..kwpwk..',
    '..kLwLk..kpppk..',
    '...kLk...kpwpk..',
    '...kLk....kpk...',
    '...kLk....kpk...',
    '...kLk....kpk...',
    '..kLLLk...kpk...',
    '..kLwLk..kpppk..',
    '..kLLLk..kpwpk..',
    '...kkk...kpppk..',
  ],
  nuoc_rua_chen: [
    '......kkkk......',
    '......kwwk......',
    '......kwwk......',
    '.....kkkkkk.....',
    '....knnnnnnk....',
    '...knwnnnnnnk...',
    '...knnnnnnnnk...',
    '...kwwwwwwwwk...',
    '...kwwyyyywwk...',
    '...kwyyyyyywk...',
    '...kwwyyyywwk...',
    '...kwwwwwwwwk...',
    '...knnnnnnnnk...',
    '...knnnnnnnnk...',
    '...kNNNNNNNNk...',
    '....kkkkkkkk....',
  ],
  bot_giat: [
    '................',
    '.kkkkkkkkkkkkkk.',
    'kLlLlLlLlLlLlLlk',
    'kLLLLLLLLLLLLLLk',
    'kLLwwwwLLLLLLLLk',
    'kLwllllwLLLLLLLk',
    'kLwllllwLLLwwLLk',
    'kLLwwwwLLLwllwLk',
    'kLLLLLLLLLLwwLLk',
    'kLLrrrrrrrrrrLLk',
    'kLLrwwwwwwwwrLLk',
    'kLLrrrrrrrrrrLLk',
    'kLLLLLLLLLLLLLLk',
    'kLlLlLlLlLlLlLlk',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  tui_rac: [
    '................',
    '.....kk..kk.....',
    '....kddkkddk....',
    '.....kddddk.....',
    '......kddk......',
    '.....kkddkk.....',
    '....kddddddk....',
    '...kdgddddddk...',
    '..kdgddddddddk..',
    '.kdgddddddddddk.',
    '.kddddddddddddk.',
    '.kddddddddddgdk.',
    '.kddddddddddddk.',
    '..kddddddddddk..',
    '...kkkkkkkkkk...',
    '................',
  ],
  dau_goi: [
    '......kkkk......',
    '.....kVVVVk.....',
    '.....kkkkkk.....',
    '.....kvvvvk.....',
    '....kvvvvvvk....',
    '...kvwvvvvvvk...',
    '...kvwvvvvvvk...',
    '...kvvvvvvvvk...',
    '...kwwwwwwwwk...',
    '...kwppwwppwk...',
    '...kwwwwwwwwk...',
    '...kvvvvvvvvk...',
    '...kvvvvvvvvk...',
    '...kVVVVVVVVk...',
    '....kkkkkkkk....',
    '................',
  ],
  nhang_muoi: [
    '...........g....',
    '............g...',
    '...kkkkkkkkkko..',
    '..knnnnnnnnnnk..',
    '..knkkkkkkkknk..',
    '..knknnnnnnknk..',
    '..knknkkkknknk..',
    '..knknknnknknk..',
    '..knknknnknknk..',
    '..knknkkkknknk..',
    '..knknnnnnnknk..',
    '..knkkkkkkkknk..',
    '..knnnnnnnnnnk..',
    '...kkkkkkkkkk...',
    '................',
    '................',
  ],
  khau_trang: [
    '................',
    '................',
    '................',
    '...kkkkkkkkkk...',
    '.kkiiiiiiiiiikk.',
    'k.kllllllllllk.k',
    'k.kiiiiiiiiiik.k',
    'k.kllllllllllk.k',
    'k.kiiiiiiiiiik.k',
    'k.kllllllllllk.k',
    '.kkiiiiiiiiiikk.',
    '...kkkkkkkkkk...',
    '................',
    '................',
    '................',
    '................',
  ],
  nhang: [
    '................',
    '.....g..g..g....',
    '....g..g..g.....',
    '....o.o.o.o.o...',
    '....t.t.t.t.t...',
    '....t.t.t.t.t...',
    '....t.t.t.t.t...',
    '...kkkkkkkkkkk..',
    '...kyyyyyyyyyk..',
    '...krrrrrrrrrk..',
    '...krrrrrrrrrk..',
    '...kryyyyyyyrk..',
    '...krrrrrrrrrk..',
    '...krrrrrrrrrk..',
    '...kkkkkkkkkkk..',
    '................',
  ],
  nuoc_lau_san: [
    '......kkkk......',
    '......kvvk......',
    '......kkkk......',
    '.....kppppk.....',
    '....kppppppk....',
    '..kkppppppppkk..',
    '..kpwppppppppk..',
    '..kpwppppppppk..',
    '..kwwwwwwwwwwk..',
    '..kwwvwwwwvwwk..',
    '..kwvvvwwvvvwk..',
    '..kwwvwwwwvwwk..',
    '..kwwwwwwwwwwk..',
    '..kppppppppppk..',
    '..kvvvvvvvvvvk..',
    '...kkkkkkkkkk...',
  ],
  bang_ve_sinh: [
    '................',
    '.kkkkkkkkkkkkkk.',
    'kppppppppppppppk',
    'kpwppppppppppppk',
    'kppppwwwwwwppppk',
    'kpppwwqqqqwwpppk',
    'kppwwqqqqqqwwppk',
    'kppwwqqqqqqwwppk',
    'kpppwwqqqqwwpppk',
    'kppppwwwwwwppppk',
    'kppppppppppppppk',
    'kpLLLLLLLLLLLLpk',
    'kppppppppppppppk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  bong_den: [
    '................',
    '.....kkkkkk.....',
    '....kyyyyyyk....',
    '...kywwyyyyyk...',
    '...kywyyyyyyk...',
    '...kyyyyyyyyk...',
    '...kyyyyyyyyk...',
    '....kyyyyyyk....',
    '.....kyyyyk.....',
    '.....kssssk.....',
    '.....kSSSSk.....',
    '.....kssssk.....',
    '.....kSSSSk.....',
    '......kddk......',
    '.......kk.......',
    '................',
  ],
  ta_giay: [
    '................',
    '.kkkkkkkkkkkkkk.',
    'kllllllllllllllk',
    'klwllllllllllllk',
    'kllkkkkkkkkkkllk',
    'kllkcccccccckllk',
    'kllkckcccckckllk',
    'kllkpccccccpkllk',
    'kllkccckkccckllk',
    'kllkkkkkkkkkkllk',
    'kllllllllllllllk',
    'kLLLLLLLLLLLLLLk',
    'kllllllllllllllk',
    'kllllllllllllllk',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  sua_dau_nanh: [
    '................',
    '......kkkk......',
    '......knnk......',
    '......kNNk......',
    '.....kcccck.....',
    '....kcwcccck....',
    '....kcwcccck....',
    '....knnnnnnk....',
    '....knyyyynk....',
    '....knyYyynk....',
    '....knnnnnnk....',
    '....kcccccck....',
    '....kcccccck....',
    '....kcccccck....',
    '....kttttttk....',
    '.....kkkkkk.....',
  ],
  bia_lon: [
    '................',
    '....kkkkkkkk....',
    '...kssssssssk...',
    '...kSSSSSSSSk...',
    '...kyyyyyyyyk...',
    '...kywyyyyyyk...',
    '...kywyyyyyyk...',
    '...kwwwwwwwwk...',
    '...kwrrrrrrwk...',
    '...kwwwwwwwwk...',
    '...kyyyyyyyyk...',
    '...kyyyyyyyyk...',
    '...kYYYYYYYYk...',
    '...kSSSSSSSSk...',
    '....kkkkkkkk....',
    '................',
  ],
  ca_phe_lon: [
    '................',
    '....kkkkkkkk....',
    '...kssssssssk...',
    '...kSSSSSSSSk...',
    '...kbbbbbbbbk...',
    '...kbwbbbbbbk...',
    '...kbwbbbbbbk...',
    '...kcccccccck...',
    '...kcceeeecck...',
    '...kcceBBecck...',
    '...kcccccccck...',
    '...kbbbbbbbbk...',
    '...kBBBBBBBBk...',
    '...kSSSSSSSSk...',
    '....kkkkkkkk....',
    '................',
  ],
  nuoc_cam: [
    '................',
    '......kkkk......',
    '......kNNk......',
    '......kkkk......',
    '......kook......',
    '.....kooook.....',
    '....kowooook....',
    '....kooooook....',
    '....kwwwnwwk....',
    '....kwwoowwk....',
    '....kwoooowk....',
    '....kwwoowwk....',
    '....kwwwwwwk....',
    '....kooooook....',
    '....kooooook....',
    '.....kkkkkk.....',
  ],
  nuoc_yen: [
    '................',
    '....kkkkkkkk....',
    '...kyyyyyyyyk...',
    '...kYYYYYYYYk...',
    '...krrrrrrrrk...',
    '...krwrrrrrrk...',
    '...kyyyyyyyyk...',
    '...kytttttttk...',
    '...kytcttctyk...',
    '...kyyttttyyk...',
    '...kyyyyyyyyk...',
    '...krrrrrrrrk...',
    '...kRRRRRRRRk...',
    '...kYYYYYYYYk...',
    '....kkkkkkkk....',
    '................',
  ],
  sua_chua_uong: [
    '................',
    '................',
    '................',
    '......kkkk......',
    '.....krrrrk.....',
    '.....kkkkkk.....',
    '.....kqqqqk.....',
    '......kqqk......',
    '.....kqqqqk.....',
    '....kqwqqqqk....',
    '....kqwqqqqk....',
    '....kppppppk....',
    '....kpwwwwpk....',
    '....kppppppk....',
    '.....kkkkkk.....',
    '................',
  ],
  ca_chua: [
    '................',
    '................',
    '.......kk.......',
    '.....knNNnk.....',
    '...kkrnnnnrkk...',
    '..krrrrnnrrrrk..',
    '.krwwrrrrrrrrrk.',
    '.krwrrrrrrrrrrk.',
    '.krrrrrrrrrrrrk.',
    '.krrrrrrrrrrrrk.',
    '.krrrrrrrrrrrRk.',
    '.kRrrrrrrrrrRRk.',
    '..kRrrrrrrrRRk..',
    '...kkRRRRRRkk...',
    '.....kkkkkk.....',
    '................',
  ],
  hanh_la: [
    '...k...k...k....',
    '..knk.knk.knk...',
    '..knk.knk.knk...',
    '..kNk.knk.kNk...',
    '..knk.kNk.knk...',
    '..knkkknkkknk...',
    '...knNnnnNnk....',
    '...knnNnnnnk....',
    '...knnnnNnnk....',
    '...krrrrrrrk....',
    '...kwwwwwwwk....',
    '...kwwwwwwwk....',
    '....kwwwwwk.....',
    '....kkkkkkk.....',
    '....t.t.t.t.....',
    '.....t.t.t......',
  ],
  sua_chua: [
    '................',
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kssssssssssk..',
    '..kSSSSSSSSSSk..',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kwwrrwwwwk...',
    '...kwrrrrwwwk...',
    '....kwwwwwwk....',
    '....kppppppk....',
    '....kppppppk....',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  chuoi: [
    '................',
    'kk..............',
    'kbk..........kk.',
    'kBkkk......kkyk.',
    'kbkwykkkkkkyyyk.',
    '.kkyyyyyyyyyykk.',
    '.kykkYYYYYYkkyk.',
    'kbkwykkkkkkyyyk.',
    '.kkyyyyyyyyyykk.',
    '.kykkYYYYYYkkyk.',
    '.kywykkkkkkyyyk.',
    '..kyyyyyyyyyyk..',
    '...kkYYYYYYkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  khoai_tay: [
    '................',
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkttttttkk...',
    '..ktwttttttttk..',
    '.kttttttteetttk.',
    '.ktteettttttttk.',
    '.kttttttttteetk.',
    '.ktttteetttttek.',
    '..kettttttttte..',
    '...kkeeeeeekk...',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
  ],
  bun_tuoi: [
    '................',
    '................',
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkwcwcwckk...',
    '..kwcwcwcwcwck..',
    '.kwcwcwcwcwcwck.',
    '.kcwcwcwcwcwcwk.',
    '.kwcwcwcwcwcwck.',
    'knnnnnnnnnnnnnnk',
    '.kNNNNNNNNNNNNk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ],
  cha_lua: [
    '................',
    '................',
    '.....kkkkkk.....',
    '...kknnnnnnkk...',
    '..knnccccccnnk..',
    '.knccqccccqccnk.',
    '.knccccccccccnk.',
    '.kwwwwwwwwwwwwk.',
    '.knccccqccccqnk.',
    '.knccqcccccccnk.',
    '..knnccccccnnk..',
    '...kknnnnnnkk...',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
  ],
  thit_heo: [
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kwwwwwwwwwwwwk.',
    '.kwrrrrrrrrrrwk.',
    '.kwrrwrrrqrrrwk.',
    '.kwrrrrrqqrrrwk.',
    '.kwrqrrrrrrwrwk.',
    '.kwrrrrrrryyywk.',
    '.kwwwwwwwwwwwwk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ],
  ca_vien: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kLlLlLlLlLlk..',
    '..kiiiiiiiiiik..',
    '..kiwciwciwcik..',
    '..kictictictik..',
    '..kiiiiiiiiiik..',
    '..kiiwciwciiik..',
    '..kiictictiiik..',
    '..kiiiiiiiiiik..',
    '..klrrrrrrrrlk..',
    '..kllllllllllk..',
    '..kLlLlLlLlLlk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  bo_vien: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kRrRrRrRrRrk..',
    '..kwwwwwwwwwwk..',
    '..kwtbwtbwtbwk..',
    '..kwbBwbBwbBwk..',
    '..kwwwwwwwwwwk..',
    '..kwwtbwtbwwwk..',
    '..kwwbBwbBwwwk..',
    '..kwwwwwwwwwwk..',
    '..kryyyyyyyyrk..',
    '..krrrrrrrrrrk..',
    '..kRrRrRrRrRrk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  canh_ga: [
    '................',
    '.......kkkkk....',
    '..i...koooook...',
    '..i..kowoooook..',
    '.i.i.kwooooooek.',
    '.....koooooooek.',
    '.....kooooooeek.',
    '......kooooeek..',
    '.......koeeek...',
    '........kwwk....',
    '........kwwk....',
    '.......kwwwwk...',
    '......kwwkkwwk..',
    '.......kk..kk...',
    '................',
    '................',
  ],
  tom_dong_lanh: [
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkooooookk...',
    '..koowooooooRk..',
    '.koooookkkkoRk..',
    '.kooookk..kkk...',
    '.kRoook.........',
    '.kooook.........',
    '.kRoooRk....kk..',
    '..kooooRkkkkok..',
    '...kkoooooookk..',
    '.....kkkkooRok..',
    '.........kk.kk..',
    '................',
    '................',
  ],
  sim_dt: [
    '................',
    '................',
    '...kkkkkkkk.....',
    '...knnnnnnnk....',
    '...knnnnnnnnk...',
    '...knkkkkkknk...',
    '...knkyYYyknk...',
    '...knkYyyYknk...',
    '...knkyYYyknk...',
    '...knkkkkkknk...',
    '...knnnnnnnnk...',
    '...knwwwnnnnk...',
    '...knnnnnnnnk...',
    '...kkkkkkkkkk...',
    '................',
    '................',
  ],
} satisfies Record<string, Sprite>);

// Lô hàng đa dạng cho tiệm lớn hơn: gói khô, bánh kẹo, chăm sóc cá nhân,
// rau thịt, đồ đông lạnh và đồ uống đều có sprite riêng theo cùng phong cách pixel.
Object.assign(PRODUCT_SPRITES, {
  ca_moi_hop: groceryJar8('r', 'w', 'Y'),
  dau_do: groceryBag8('R', 'r', 't'),
  bot_cacao: groceryBag8('b', 't', 'Y'),
  bot_cari: groceryBag8('Y', 'o', 'r'),
  ngu_vi_huong: groceryJar8('t', 'Y', 'b'),
  sa_te: groceryJar8('r', 'Y', 'R'),
  dau_nanh_hat: groceryBag8('Y', 'n', 't'),
  mi_y_kho: groceryBag8('Y', 'r', 'o'),
  banh_quy_oreo: groceryBag8('b', 'w', 'L'),
  banh_chocopie: groceryBag8('b', 'r', 'Y'),
  snack_khoai_tay: groceryBag8('Y', 'o', 'r'),
  socola_thanh: groceryBag8('b', 't', 'R'),
  bap_rang_caramel: groceryBag8('Y', 'w', 'o'),
  banh_cracker: groceryBag8('t', 'Y', 'b'),
  rong_bien_cuon: groceryBag8('n', 'w', 'N'),
  keo_bac_ha: groceryBag8('l', 'w', 'n'),
  sua_bot_tre_em: groceryCarton8('w', 'p', 'q'),
  nuoc_suc_mieng: drinkBottle8('L', 'w', 'l'),
  sua_rua_mat: drinkBottle8('p', 'w', 'q'),
  kem_duong_da: groceryJar8('w', 'p', 'q'),
  giay_khan_mat: groceryCarton8('w', 'L', 's'),
  mieng_rua_chen: groceryBag8('n', 'Y', 'o'),
  binh_xit_con_trung: drinkBottle8('n', 'Y', 'r'),
  xa_lach: pixelSprite8('...nn...', '..knnk..', '.knnnNk.', 'knnwwnnk', 'knnNnnnk', '.knnnnk.', '..knnk..', '...kk...'),
  dua_gia: pixelSprite8('..k.k...', '.knknk..', 'knnnnnk.', '.knnkn..', 'knnknnk.', '.knnnk..', '..kk....', '........'),
  khoai_mon: pixelSprite8('........', '..kkk...', '.kvvvVk.', 'kvvVvvvk', 'kvvvvvvk', '.kvvvVk.', '..kkk...', '........'),
  nam_bao_ngu: pixelSprite8('..kkkk..', '.kwwwwk.', 'kwwWwwwk', '.knnNnk.', '..knnk..', '..knnk..', '..knnk..', '..kkkk..'),
  ca_ro_phi: pixelSprite8('........', '..kkk...', '.kLLLk..', 'kLtwwLk.', '.kLLLkk.', '..kkkk..', '........', '........'),
  muc_tuoi: pixelSprite8('........', '..kkkk..', '.kwwwwk.', 'kwwWwwk.', '.kwwwwk.', '..kwwk..', '.k.k.k..', '........'),
  thit_xay: pixelSprite8('........', '..kkkk..', '.krrrrk.', 'krrRrrrk', 'krrwwrrk', '.krrrrk.', '..kkkk..', '........'),
  ca_hoi_tuoi: pixelSprite8('........', '..kkk...', '.ktRttk.', 'ktRwwttk', '.ktRttkk', '..kkkk..', '........', '........'),
  cha_muc: groceryBag8('w', 's', 'L'),
  vien_tha_lau: groceryBag8('t', 'r', 'Y'),
  ca_hoi_dong_lanh: groceryBag8('p', 'w', 'L'),
  bap_non_dong_lanh: groceryBag8('Y', 'n', 'L'),
  milo_hop: drinkCarton8('b', 'w', 'R'),
  sua_dau_nanh_hop: drinkCarton8('Y', 'n', 'w'),
  tra_sua_chai: drinkBottle8('b', 't', 'B'),
  nuoc_dua_tuoi_chai: drinkBottle8('w', 'n', 't'),
  nuoc_cam_hop: drinkCarton8('o', 'Y', 'r'),
  ca_phe_sua_lon: drinkCan8('b', 'w', 'Y'),
  nuoc_sam: drinkBottle8('b', 'Y', 'n'),
} satisfies Record<string, Sprite>);

// Các biến thể nước đóng lon/chai/hộp có cùng dáng bao bì nhưng phối màu và nhãn pixel riêng.
function drinkCan8(body: string, label: string, detail: string): Sprite {
  return pixelSprite8(
    '...ss...', `...k${body}k..`, `.k${body.repeat(4)}k.`, `k${body.repeat(6)}k`,
    `k${body}${label}${label}${body.repeat(3)}k`, `k${body}${detail}${detail}${body.repeat(3)}k`,
    `.k${body.repeat(4)}k.`, '..kkkk..',
  );
}

function drinkBottle8(body: string, label: string, cap: string): Sprite {
  return pixelSprite8(
    `..k${cap}k...`, `...k${body}k..`, `..k${body.repeat(2)}k..`, `.k${body.repeat(4)}k.`,
    `k${body}${label}${label}${body.repeat(3)}k`, `k${body.repeat(6)}k`, `.k${body.repeat(4)}k.`, '..kkkk..',
  );
}

function drinkCarton8(body: string, label: string, top: string): Sprite {
  return pixelSprite8(
    `..k${top.repeat(2)}k..`, `.k${body.repeat(4)}k.`, `k${body.repeat(6)}k`,
    `k${body}${label}${label}${body.repeat(3)}k`, `k${body.repeat(6)}k`,
    `k${body}${top}${top}${body.repeat(3)}k`, `.k${body.repeat(4)}k.`, '..kkkk..',
  );
}

Object.assign(PRODUCT_SPRITES, {
  coca_cola_plus: drinkCan8('r', 'w', 'Y'),
  pepsi_chanh: drinkCan8('L', 'y', 'n'),
  fanta_nho: drinkCan8('v', 'w', 'V'),
  fanta_dau: drinkCan8('R', 'p', 'r'),
  mirinda_vai: drinkCan8('p', 'w', 'r'),
  mirinda_dua: drinkCan8('o', 'Y', 'y'),
  schweppes_tonic: drinkCan8('s', 'w', 'L'),
  aquafina_soda: drinkCan8('L', 'i', 'w'),
  milkis_dua_gang: drinkCan8('l', 'w', 'n'),
  milkis_chuoi: drinkCan8('Y', 'w', 'y'),
  soda_vai_genki: drinkBottle8('p', 'w', 'V'),
  tea_plus_oolong_chanh: drinkBottle8('n', 'y', 'N'),
  tea_plus_oolong_dao: drinkBottle8('t', 'p', 'r'),
  tea_plus_oolong_truyen_thong: drinkBottle8('n', 'w', 'N'),
  fuze_tea_bi_dao: drinkBottle8('n', 'Y', 'N'),
  fuze_tea_chanh_sa: drinkBottle8('n', 'y', 'N'),
  fuze_tea_vai: drinkBottle8('p', 'w', 'V'),
  twister_cam: drinkBottle8('o', 'Y', 'r'),
  nuoc_nho_trang_gas: drinkBottle8('c', 'Y', 'w'),
  nuoc_tao_ep: drinkCarton8('r', 'w', 'Y'),
  nuoc_le_ep: drinkCarton8('n', 'w', 'Y'),
  nuoc_luu: drinkCarton8('R', 'p', 'r'),
  yakult: drinkBottle8('w', 'r', 'r'),
  yomost_dau: drinkCarton8('p', 'w', 'r'),
  yomost_luu: drinkCarton8('R', 'w', 'p'),
  probi_dao: drinkBottle8('t', 'p', 'r'),
  betagen_cam: drinkBottle8('o', 'w', 'r'),
  ca_phe_sua_chai: drinkBottle8('b', 'c', 'B'),
  sua_socola_hop: drinkCarton8('B', 'c', 'b'),
  sua_dau_phong: drinkCarton8('t', 'Y', 'b'),
} satisfies Record<string, Sprite>);

// Hàng bổ sung (vẽ từ các khuôn chai / lon / hộp / gói / túi dùng chung).
Object.assign(PRODUCT_SPRITES, {
  tra_o_long: [
    '......kkkk......', '......krrk......', '......krrk......', '.....kYYYYk.....',
    '....kYYYYYYk....', '....kYwYYYYk....', '....knnnnnnk....', '....knwwwwnk....',
    '....knnnnnnk....', '....kYYYYYYk....', '....kYYYYYYk....', '....kYYYYYYk....',
    '....kYYYYYYk....', '....kYYYYYYk....', '.....kkkkkk.....', '................',
  ],
  sua_lua_mach: [
    '................', '................', '...kkkkkkkkkk...', '...knnnnnnnnk...',
    '...knnnnnnnnk...', '...knwnnnnnnk...', '...knnnnnnnnk...', '...kBBBBBBBBk...',
    '...kBwwwwwwBk...', '...kBBBBBBBBk...', '...knnnnnnnnk...', '...knnnnnnnnk...',
    '...knnnnnnnnk...', '...kkkkkkkkkk...', '................', '................',
  ],
  nuoc_dien_giai: [
    '......kkkk......', '......kwwk......', '......kwwk......', '.....kllllk.....',
    '....kllllllk....', '....klwllllk....', '....kLLLLLLk....', '....kLwwwwLk....',
    '....kLLLLLLk....', '....kllllllk....', '....kllllllk....', '....kllllllk....',
    '....kllllllk....', '....kllllllk....', '.....kkkkkk.....', '................',
  ],
  nuoc_dua_hop: [
    '................', '................', '...kkkkkkkkkk...', '...kNNNNNNNNk...',
    '...knnnnnnnnk...', '...knwnnnnnnk...', '...knnnnnnnnk...', '...kwwwwwwwwk...',
    '...kwwwwwwwwk...', '...kwwwwwwwwk...', '...knnnnnnnnk...', '...knnnnnnnnk...',
    '...knnnnnnnnk...', '...kkkkkkkkkk...', '................', '................',
  ],
  soda_chanh: [
    '................', '................', '.....kkkkkk.....', '....kssssssk....',
    '....kyyyyyyk....', '....kywyyyyk....', '....knnnnnnk....', '....knwwnnnk....',
    '....knnnnnnk....', '....kyyyyyyk....', '....kyyyyyyk....', '....kyyyyyyk....',
    '....kssssssk....', '.....kkkkkk.....', '................', '................',
  ],
  bim_bim_tom: [
    '................', '.kkkkkkkkkkkkkk.', 'kyyyyyyyyyyyyyyk', 'koowoooooooooook',
    'kooooooooooooook', 'koorrrrrrrrrrook', 'koorwwrrrwwrrook', 'koorrrrrrrrrrook',
    'kooooooooooooook', 'kooooooooooooook', 'kooowwwwwwoooook', 'kooooooooooooook',
    'kyyyyyyyyyyyyyyk', '.kkkkkkkkkkkkkk.', '................', '................',
  ],
  keo_deo: [
    '................', '................', '....kkkkkkkk....', '...kppppppppk...',
    '...kvvvvvvvvk...', '..kvvwvvvvvvvk..', '..kvvvvvvvvvvk..', '..kvqqqqqqqqvk..',
    '..kvqwwqqwwqvk..', '..kvqqqqqqqqvk..', '..kvvvvvvvvvvk..', '..kvvvvvvvvvvk..',
    '..kvvvvvvvvvvk..', '...kkkkkkkkkk...', '................', '................',
  ],
  banh_que: [
    '................', '................', '...kkkkkkkkkk...', '...kyyyyyyyyk...',
    '...kttttttttk...', '...ktwttttttk...', '...kttttttttk...', '...krrrrrrrrk...',
    '...krwwwwwwrk...', '...krrrrrrrrk...', '...kttttttttk...', '...kttttttttk...',
    '...kttttttttk...', '...kkkkkkkkkk...', '................', '................',
  ],
  mit_say: [
    '................', '................', '....kkkkkkkk....', '...kNNNNNNNNk...',
    '...kyyyyyyyyk...', '..kyywyyyyyyyk..', '..kyyyyyyyyyyk..', '..kynnnnnnnnyk..',
    '..kynwwnnwwnyk..', '..kynnnnnnnnyk..', '..kyyyyyyyyyyk..', '..kyyyyyyyyyyk..',
    '..kyyyyyyyyyyk..', '...kkkkkkkkkk...', '................', '................',
  ],
  pho_goi: [
    '................', '.kkkkkkkkkkkkkk.', 'kRRRRRRRRRRRRRRk', 'kccwccccccccccck',
    'kcccccccccccccck', 'kccrrrrrrrrrrcck', 'kccrwwrrrwwrrcck', 'kccrrrrrrrrrrcck',
    'kcccccccccccccck', 'kcccccccccccccck', 'kcccwwwwwwccccck', 'kcccccccccccccck',
    'kRRRRRRRRRRRRRRk', '.kkkkkkkkkkkkkk.', '................', '................',
  ],
  mien_goi: [
    '................', '.kkkkkkkkkkkkkk.', 'kLLLLLLLLLLLLLLk', 'kWWwWWWWWWWWWWWk',
    'kWWWWWWWWWWWWWWk', 'kWWLLLLLLLLLLWWk', 'kWWLwwLLLwwLLWWk', 'kWWLLLLLLLLLLWWk',
    'kWWWWWWWWWWWWWWk', 'kWWWWWWWWWWWWWWk', 'kWWWwwwwwwWWWWWk', 'kWWWWWWWWWWWWWWk',
    'kLLLLLLLLLLLLLLk', '.kkkkkkkkkkkkkk.', '................', '................',
  ],
  bot_mi: [
    '................', '................', '....kkkkkkkk....', '...kyyyyyyyyk...',
    '...kwwwwwwwwk...', '..kwwwwwwwwwwk..', '..kwwwwwwwwwwk..', '..kwYYYYYYYYwk..',
    '..kwYwwYYwwYwk..', '..kwYYYYYYYYwk..', '..kwwwwwwwwwwk..', '..kwwwwwwwwwwk..',
    '..kwwwwwwwwwwk..', '...kkkkkkkkkk...', '................', '................',
  ],
  sua_tam: [
    '................', '.......kkk......', '.......kLLk.....', '......kllllkkk..',
    '.....kllllllklk.', '.....klwllllklk.', '.....kllllllklk.', '.....kwwwwwwkk..',
    '.....kwwwwwwk...', '.....kwwwwwwk...', '.....kllllllk...', '.....kllllllk...',
    '.....kllllllk...', '.....kllllllk...', '......kkkkkk....', '................',
  ],
  nuoc_giat: [
    '................', '.......kkk......', '.......krrk.....', '......kLLLLkkk..',
    '.....kLLLLLLkLk.', '.....kLwLLLLkLk.', '.....kLLLLLLkLk.', '.....kwwwwwwkk..',
    '.....kwwwwwwk...', '.....kwwwwwwk...', '.....kLLLLLLk...', '.....kLLLLLLk...',
    '.....kLLLLLLk...', '.....kLLLLLLk...', '......kkkkkk....', '................',
  ],
  nuoc_xa_vai: [
    '................', '.......kkk......', '.......kvvk.....', '......kppppkkk..',
    '.....kppppppkpk.', '.....kpwppppkpk.', '.....kppppppkpk.', '.....kwwwwwwkk..',
    '.....kwwwwwwk...', '.....kwwwwwwk...', '.....kppppppk...', '.....kppppppk...',
    '.....kppppppk...', '.....kppppppk...', '......kkkkkk....', '................',
  ],
  dao_cao: [
    '................', '................', '...kkkkkkkkkk...', '...kSSSSSSSSk...',
    '...kssssssssk...', '...kswssssssk...', '...kssssssssk...', '...kLLLLLLLLk...',
    '...kLwwwwwwLk...', '...kLLLLLLLLk...', '...kssssssssk...', '...kssssssssk...',
    '...kssssssssk...', '...kkkkkkkkkk...', '................', '................',
  ],
  kem_chong_nang: [
    '................', '................', '................', '..kkkkkkkkkk....',
    '.kooooooooookkk.', '.kowooooooookyyk', '.kowwwwwwwwokyyk', '.kowwwwwwwwokyyk',
    '.kowwwwwwwwokyyk', '.kooooooooookkk.', '..kkkkkkkkkk....', '................',
    '................', '................', '................', '................',
  ],
  rau_cai: [
    '................', '......k..k......', '.....knk.knk....', '....knnnknnnk...',
    '...knnwnnnnnk...', '...knnnnnnnnnk..', '..knnnnnnnnnnk..', '...knnnnnnnnk...',
    '....knnnnnnk....', '.....kcccck.....', '.....kNNNNk.....', '.....kcccck.....',
    '......kcck......', '......kcck......', '.......kk.......', '................',
  ],
  trung_vit: [
    '................', '................', '................', '....kkk..kkk....',
    '...kWWWk.kWWWk..', '..kWwWWWkWwWWk..', '..kWWWWWkWWWWk..', '..kWWWWkkkWWWk..',
    '.kkkWWkWWWkWkkk.', '.kttkkWwWWWkttk.', '.ktttkWWWWktttk.', '.kttttkkkkttttk.',
    '.kttttttttttttk.', '..kkkkkkkkkkkk..', '................', '................',
  ],
  gia_do: [
    '................', '................', '................', '................',
    '..kkkkkkkkkkkk..', '.kiiiiiiiiiiiik.', '.kiccccccccccik.', '.kicwccccccccik.',
    '.kicncncncnccik.', '.kiccccccccccik.', '.kinnnnnnnnnnik.', '.kiiiiiiiiiiiik.',
    '..kkkkkkkkkkkk..', '................', '................', '................',
  ],
  kem_oc_que: [
    '................', '.....kkkkk......', '....kqqqqqk.....', '...kqwqqqqqk....',
    '...kqqqqpqqk....', '...kqqqqqqqk....', '...kkkkkkkkk....', '....kptptpk.....',
    '....ktptptk.....', '.....kptpk......', '.....ktptk......', '......kpk.......',
    '......ktk.......', '.......k........', '................', '................',
  ],
  banh_bao: [
    '................', '................', '................', '.......kk.......',
    '......krrk......', '....kkwwwwkk....', '...kwwwwwwwwk...', '..kwwwwwwwwwwk..',
    '..kwwwwwwwwwwk..', '..kwwwwwwwwwwk..', '..kwwwwwwwwwwk..', '...kWWWWWWWWk...',
    '....kkkkkkkk....', '................', '................', '................',
  ],
  ca_basa: [
    '................', '................', '................', '................',
    '..kkkkkkkkkkkk..', '.kiiiiiiiiiiiik.', '.kiqqqqqqqqqqik.', '.kiqwqqqqqqqqik.',
    '.kiqWqWqWqWqqik.', '.kiqqqqqqqqqqik.', '.kiWWWWWWWWWWik.', '.kiiiiiiiiiiiik.',
    '..kkkkkkkkkkkk..', '................', '................', '................',
  ],
} satisfies Record<string, Sprite>);

// Tiệm xôi: mượn hình có sẵn (đã khai báo ở trên) cho tới khi vẽ sprite riêng.
for (const [id, source] of Object.entries({
  nep: 'gao', dau_xanh: 'dau_phong', hanh_phi: 'hat_nem', cha_bong: 'kho_ga', lap_xuong: 'xuc_xich', dua_nao: 'bot_mi',
  bao_goi: 'khan_giay', tra_da: 'tra_xanh', nep_chin: 'gao',
  xoi_dau_xanh_tp: 'banh_bao', xoi_man_tp: 'banh_bao', xoi_trung_tp: 'banh_bao', xoi_dua_tp: 'banh_bao',
  xoi_dau_xanh_goi: 'banh_bao', xoi_man_goi: 'banh_bao', xoi_trung_goi: 'banh_bao', xoi_dua_goi: 'banh_bao',
})) PRODUCT_SPRITES[id] = PRODUCT_SPRITES[source];

// Rau củ và trái cây mới: vẽ riêng theo lưới pixel 8x8, phóng mỗi pixel thành 2x2.
function pixelSprite8(...rows: string[]): Sprite {
  return rows.flatMap((row) => {
    const doubled = [...row].map((pixel) => pixel + pixel).join('');
    return [doubled, doubled];
  });
}

Object.assign(PRODUCT_SPRITES, {
  toi: pixelSprite8(
    '...kk...', '..kcck..', '.kcccck.', '.kcwwck.', '..kcck..', '...kk...', '...kk...', '........',
  ),
  hanh_kho: pixelSprite8(
    '...kk...', '..kttk..', '.kttttk.', '.ktWWtk.', '.kttttk.', '..kttk..', '...kk...', '........',
  ),
  ca_rot: pixelSprite8(
    '...nn...', '..knnk..', '..kook..', '..koYk..', '...koYk.', '....kok.', '.....kk.', '........',
  ),
  dua_leo: pixelSprite8(
    '........', '.kNNNk..', 'knnnnnk.', 'knnwnnk.', 'knnnNnk.', 'knnnnnk.', '.kNNNk..', '........',
  ),
  bap_cai: pixelSprite8(
    '...nn...', '..knnnk.', '.knwnnnk', 'knnnnnnk', 'knnnNnnk', '.knnnnnk', '..kNNNk.', '........',
  ),
  bi_do: pixelSprite8(
    '...nn...', '..knnk..', '.kYYYYk.', 'kYyYyYyk', 'kYyYyYyk', '.kYYYYk.', '..kYYk..', '........',
  ),
  bong_cai_xanh: pixelSprite8(
    '..knk...', '.knnnk..', 'knNnnnnk', 'knnnNnnk', '.knnnnk.', '..kttk..', '..kttk..', '...kk...',
  ),
  kho_qua: pixelSprite8(
    '........', '..kNNk..', '.knnnnnk', 'knNnnNnk', 'knnnnnnk', '.knnnnnk', '..kNNk..', '........',
  ),
  gung: pixelSprite8(
    '........', '..kk....', '.kttkk..', 'ktttttk.', '.ktttk..', '..ktttk.', '..kttk..', '....kk..',
  ),
  rau_mui: pixelSprite8(
    '...n....', '..knk...', '.knnnk..', 'knnNnnk.', '..knnnk.', '.knnnnk.', '..kttk..', '...kk...',
  ),
  bap: pixelSprite8(
    '...nn...', '..knnk..', '.kyyYyk.', '.kYyYyk.', '.kyyYyk.', '.kYyYyk.', '..kyyk..', '...kk...',
  ),
  tao: pixelSprite8(
    '...knk..', '..krrk..', '.krrrrk.', 'kRrrwrrk', 'krrrrrrk', '.krrrrk.', '..kkkk..', '........',
  ),
  na: pixelSprite8(
    '...kn...', '..knnk..', '.knnnNk.', 'knnnnnnk', 'knNnnnnk', '.knnnnk.', '..kNNk..', '........',
  ),
  mang_cut: pixelSprite8(
    '..nn....', '.knnk...', 'kvvvvvk.', 'kVvvVvvk', 'kvvvvvvk', '.kvvvvk.', '..kVVk..', '........',
  ),
  nho_xanh: pixelSprite8(
    '...nn...', '..knnk..', '.knnnnk.', 'knnNnnnk', '.knnnnk.', '..knnk..', '...kk...', '........',
  ),
  nho_tim: pixelSprite8(
    '...nn...', '..knnk..', '.kvvvvk.', 'kVvvVvvk', '.kvvvvk.', '..kvvk..', '...kk...', '........',
  ),
  thanh_long_trang: pixelSprite8(
    '...nn...', '..knnk..', '.krrrrk.', 'krcccrrk', 'krcwcrrk', '.krrrrk.', '..krrk..', '........',
  ),
  thanh_long_tim: pixelSprite8(
    '...nn...', '..knnk..', '.krrrrk.', 'krvvvrrk', 'krvVvrrk', '.krrrrk.', '..krrk..', '........',
  ),
  xoai: pixelSprite8(
    '...nn...', '..knnk..', '.kYYYYk.', 'kYooYyYk', 'kYooYyYk', '.kYYYYk.', '..kYYk..', '........',
  ),
  cam: pixelSprite8(
    '...kn...', '..koYk..', '.koooYk.', 'koowooYk', 'kYooooYk', '.kYYYYk.', '..kYYk..', '........',
  ),
  dua_hau: pixelSprite8(
    '........', '.kNNNNk.', 'knnnnnnk', 'knrrrrnk', 'knrkrRnk', '.knnnnk.', '..kkkk..', '........',
  ),
  du_du: pixelSprite8(
    '...nn...', '..knnk..', '.kYYYYk.', 'kYooYyYk', 'kYyooYYk', '.kYYYYk.', '..kYYk..', '........',
  ),
  thom: pixelSprite8(
    '...n.n..', '..knnnk.', '...kYk..', '..kYYYk.', '.kYyYYk.', '.kYYYyk.', '..kYYk..', '...kk...',
  ),
  oi: pixelSprite8(
    '...nn...', '..knnk..', '.knnnNk.', 'knnnnnnk', 'knwnnnnk', '.knnnnk.', '..kNNk..', '........',
  ),
  bo: pixelSprite8(
    '...nn...', '..knnk..', '.kNNNNk.', 'knnnnnNk', 'knnnnnNk', '.knnNnk.', '..kNNk..', '........',
  ),
  mit: pixelSprite8(
    '...nn...', '..knnk..', '.kYYYYk.', 'kYyYyYYk', 'kYYYYyYk', '.kYYYYk.', '..kYYk..', '........',
  ),
  chom_chom: pixelSprite8(
    '...nn...', '.krkrk..', 'krRrRrk.', '.krRrRrk', 'krRrRrk.', '.krRrk..', '..krk...', '........',
  ),
  vai: pixelSprite8(
    '....nn..', '...knnk.', '..krrk..', '.krrrrk.', '..krrk..', '...kk...', '........', '........',
  ),
  buoi: pixelSprite8(
    '...kn...', '..kYYk..', '.kYYYYk.', 'kYyYYyyk', 'kYYYYYyk', '.kYYYYk.', '..kYYk..', '........',
  ),
  chanh_day: pixelSprite8(
    '........', '..kvvk..', '.kvVVvvk', 'kvvvvvvk', 'kvVwVvvk', '.kvvvvvk', '..kVVk..', '........',
  ),
  banh_trang: pixelSprite8(
    '........', '..kkkk..', '.kcccck.', 'kcttttck', 'kctwwtck', 'kcttttck', '.kcccck.', '..kkkk..',
  ),
  bot_nang: pixelSprite8(
    '...kk...', '..kcck..', '.kcccck.', 'kccwwcck', 'kcccccck', 'kccYccck', '.kcccck.', '..kkkk..',
  ),
  bot_gao: pixelSprite8(
    '...kk...', '..kcck..', '.kcccck.', 'kccwccck', 'kcccccck', 'kccYccck', '.kcccck.', '..kkkk..',
  ),
  nui_kho: pixelSprite8(
    '........', '.kYYYYk.', 'kYyYyYYk', 'kYyYyYYk', '.kYYYYk.', '..kYYk..', '..kYYk..', '........',
  ),
  mi_trung_kho: pixelSprite8(
    '........', '..kkkk..', '.kYYYYk.', 'kYyYyYyk', 'kYyYyYyk', '.kYYYYk.', '..kYYk..', '...kk...',
  ),
  mien_dong: pixelSprite8(
    '........', '..kkkk..', '.kccck..', 'kcccccck', 'kccwccck', '.kcccck.', '..kcck..', '...kk...',
  ),
  nam_meo_kho: pixelSprite8(
    '........', '...kk...', '..kbbk..', '.kBBBBk.', 'kBbBBbbk', '..kBBk..', '..kbbk..', '...kk...',
  ),
  nam_huong_kho: pixelSprite8(
    '........', '...kk...', '..kttk..', '.kttttk.', 'kttWtWtk', '..kttk..', '..ktk...', '...kk...',
  ),
  tom_kho: pixelSprite8(
    '........', '..krr...', '.krRrk..', 'krRRrrk.', '.krRrrk.', '..krRk..', '...kk...', '........',
  ),
  ca_kho: pixelSprite8(
    '........', '..kkk...', '.ktttk..', 'kttwttk.', 'kttttttk', '.ktttk..', '..kkk...', '........',
  ),
  ot_bot: pixelSprite8(
    '...kk...', '..krrk..', '.krrrrk.', 'krrrrrrk', 'krrrrrrk', '.krrrrk.', '..kkkk..', '..krrk..',
  ),
  tieu_hat: pixelSprite8(
    '...kk...', '..kcck..', '.kcccck.', 'kcckkcck', 'kcckkcck', '.kcccck.', '..kcck..', '..kkkk..',
  ),
  dua_cot_hop: pixelSprite8(
    '...kk...', '..kwwk..', '.kcccck.', 'kccwwcck', 'kcccccck', 'kcccccck', '.kcccck.', '..kkkk..',
  ),
  bap_rang_bo: pixelSprite8(
    '........', '..kkkk..', '.kYYYYk.', 'kYwYwYYk', 'kYYwYwYk', '.kYYYYk.', '..kttk..', '..kkkk..',
  ),
  snack_bap: pixelSprite8(
    '........', '.kkkkkk.', 'kYYYYYYk', 'kYyYwYYk', 'kYYyYYyk', 'kYYYYYYk', '.kYYYYk.', '..kkkk..',
  ),
  banh_xop: pixelSprite8(
    '........', '.kkkkkk.', 'kttttttk', 'ktwttwtk', 'kttttttk', 'ktwttwtk', 'kttttttk', '.kkkkkk.',
  ),
  banh_trang_nuong: pixelSprite8(
    '........', '..kkkk..', '.kttttk.', 'kttYYYYk', 'kYtYwYtk', 'kYYYYYYk', '.kttttk.', '..kkkk..',
  ),
  com_chay: pixelSprite8(
    '........', '..kkkk..', '.kYYYYk.', 'kYtYtYYk', 'kYtYtYYk', '.kYYYYk.', '..kYYk..', '........',
  ),
  kho_bo: pixelSprite8(
    '........', '.kkkkkk.', 'kBBBBBBk', 'kBtttBBk', 'kBtBBtBk', 'kBtttBBk', '.kBBBBk.', '..kkkk..',
  ),
  kho_muc: pixelSprite8(
    '........', '..krrk..', '.krRrk..', 'krrrrrrk', '.krrrk..', '..krrk..', '.k.k.k..', '........',
  ),
  keo_mut: pixelSprite8(
    '........', '...kkkk.', '..kpppk.', '.kpppppk', '.kpwpppk', '..kpppk.', '...ktk..', '...ktk..',
  ),
  keo_lac: pixelSprite8(
    '........', '..kkkk..', '.kYYttk.', 'kYtYYttk', 'kYYtYttk', '.kYtYk..', '..kkkk..', '........',
  ),
  banh_dau_xanh: pixelSprite8(
    '........', '.kkkkkk.', 'kcccccck', 'kcYYccck', 'kcYYYYck', 'kccYYcck', '.kcccck.', '..kkkk..',
  ),
  hat_dieu_rang: pixelSprite8(
    '........', '..kkk...', '.ktttk..', 'ktttttk.', 'ktYtttk.', '.ktttk..', '..kkk...', '........',
  ),
  hat_huong_duong: pixelSprite8(
    '........', '..knk...', '.knnnnk.', 'knnyynk.', '.knnNnk.', '..kNNk..', '...kk...', '........',
  ),
  me_say: pixelSprite8(
    '........', '..kkkk..', '.kBBBBk.', 'kBttttBk', 'kBtttBBk', '.kBBBBk.', '..kBBk..', '........',
  ),
  mut_dua: pixelSprite8(
    '........', '..kkkk..', '.kccck..', 'kccwwcck', '.kccck..', 'kccwwcck', '.kccck..', '..kkkk..',
  ),
  khoai_lang_say: pixelSprite8(
    '........', '..kkkk..', '.kbbbk..', 'kbtYtbk.', 'kbYtYbk.', '.kbtbk..', '..kkkk..', '........',
  ),
  coca_cola_lon: pixelSprite8(
    '...kk...', '..krrk..', '.krrrrk.', 'krrrrrrk', 'krrwwrrk', 'krrrrrrk', '.krrrrk.', '..kkkk..',
  ),
  coca_cola_zero: pixelSprite8(
    '...kk...', '..kkkk..', '.kBBBBk.', 'kBBBBBBk', 'kBwwBBBk', 'kBBBBBBk', '.kBBBBk.', '..kkkk..',
  ),
  pepsi_lon: pixelSprite8(
    '...kk...', '..krrk..', '.kLLLLk.', 'kLLLLLLk', 'kLwwLLLk', 'kLLLLLLk', '.kLLLLk.', '..kkkk..',
  ),
  pepsi_black: pixelSprite8(
    '...kk...', '..kkkk..', '.kBBBBk.', 'kBBLLBBk', 'kBwwBBBk', 'kBBBBBBk', '.kBBBBk.', '..kkkk..',
  ),
  '7up_lon': pixelSprite8(
    '...kk...', '..knnk..', '.knnnNk.', 'knnwwnnk', 'knnnnnNk', 'kNnnnnnk', '.knnnnk.', '..kkkk..',
  ),
  sprite_lon: pixelSprite8(
    '...kk...', '..kLLk..', '.kLLLLk.', 'kLwwLLLk', 'kLnnLLLk', 'kLLLLLLk', '.kLLLLk.', '..kkkk..',
  ),
  mirinda_cam: pixelSprite8(
    '...kk...', '..koYk..', '.koooYk.', 'koowooYk', 'koooooYk', 'kYooooYk', '.kYYYYk.', '..kkkk..',
  ),
  sting_dau: pixelSprite8(
    '...kk...', '..krrk..', '.kppppk.', 'krrppppk', 'krwwrrrk', 'krrrrrrk', '.krrrrk.', '..kkkk..',
  ),
  sting_nhan_sam: pixelSprite8(
    '...kk...', '..krrk..', '.kYYYYk.', 'kYtYYyYk', 'kYwwYYYk', 'kYYYYYYk', '.kYYYYk.', '..kkkk..',
  ),
  redbull_lon: pixelSprite8(
    '...kk...', '..krrk..', '.kLLLLk.', 'kLLyyLLk', 'kLwwyyLk', 'kLLLLLLk', '.kLLLLk.', '..kkkk..',
  ),
  number1_chai: pixelSprite8(
    '...kk...', '..krrk..', '.krrrrk.', 'krrrrrrk', 'krrwwrrk', 'krrrrrrk', '.krrrrk.', '..kkkk..',
  ),
  aquafina_chai: pixelSprite8(
    '...kk...', '...kLL..', '..kLLk..', '.kLwwLk.', '.kLLLLk.', '..kLLk..', '..kLLk..', '...kk...',
  ),
  la_vie_chai: pixelSprite8(
    '...kk...', '...knn..', '..knnk..', '.knwnk..', '.knnnk..', '..knnk..', '..knnk..', '...kk...',
  ),
  revive_chai: pixelSprite8(
    '...kk...', '...kLL..', '..kLLk..', '.kLwwLk.', '.kLLLLk.', '..kLLk..', '..kLLk..', '...kk...',
  ),
  pocari_sweat: pixelSprite8(
    '...kk...', '...kLL..', '..kllk..', '.kLwwLk.', '.kllllk.', '..kLLk..', '..kLLk..', '...kk...',
  ),
  tra_dao_chai: pixelSprite8(
    '...kk...', '...krr..', '..krrk..', '.krrrk..', '.krwwrk.', '..krrk..', '..krrk..', '...kk...',
  ),
  sua_bap_hop: pixelSprite8(
    '..kkkk..', '.kYYYYk.', 'kYYYYYYk', 'kYwYYYYk', 'kYYYYYYk', 'kYyYyYyk', 'kYYYYYYk', '.kkkkkk.',
  ),
  nuoc_nha_dam: pixelSprite8(
    '..kkkk..', '.knnnnk.', 'knnnnnnk', 'knwwnnnk', 'knnNnnnk', 'knnnnnnk', 'knnnnnnk', '.kkkkkk.',
  ),
} satisfies Record<string, Sprite>);

function groceryBag8(body: string, label: string, seal: string): Sprite {
  return pixelSprite8(
    '..kssk..', `.k${body.repeat(4)}k.`, `k${body.repeat(6)}k`,
    `k${body}${label}${label}${body.repeat(3)}k`, `k${body.repeat(6)}k`,
    `k${body}${seal}${seal}${body.repeat(3)}k`, `.k${body.repeat(4)}k.`, '..kkkk..',
  );
}

function groceryJar8(body: string, label: string, lid: string): Sprite {
  return pixelSprite8(
    `..k${lid.repeat(2)}k..`, `.k${lid.repeat(4)}k.`, `.k${body.repeat(4)}k.`,
    `k${body.repeat(6)}k`, `k${body}${label}${label}${body.repeat(3)}k`,
    `k${body.repeat(6)}k`, '.kssssk.', '..kkkk..',
  );
}

Object.assign(PRODUCT_SPRITES, {
  hanh_tay: pixelSprite8(
    '...kk...', '..kttk..', '.kttttk.', 'kttWtttk', 'kttttttk', '.kttttk.', '..kttk..', '...kk...',
  ),
  ot_chuong: pixelSprite8(
    '...nn...', '..knnk..', '.knnnNk.', 'knnwwnnk', 'knnnnnNk', '.knnnnk.', '..kNNk..', '...kk...',
  ),
  ca_tim: pixelSprite8(
    '...nn...', '..knnk..', '.kvvvVk.', 'kvvVvvvk', '.kvvvvvk', '..kvvvk.', '...kk...', '........',
  ),
  nam_kim_cham: pixelSprite8(
    '.k.k.k..', 'kccckcck', '.kccck..', '..kcck..', '..kcck..', '..kcck..', '..kcck..', '..kkkk..',
  ),
  khoai_lang_tuoi: pixelSprite8(
    '........', '..kkk...', '.kttttk.', 'kttYtttk', 'kttttttk', '.kttttk.', '..kkk...', '........',
  ),
  chanh_khong_hat: pixelSprite8(
    '...nn...', '..knnk..', '.knnnNk.', 'knnYnnnk', 'knnnnnNk', '.knnnnk.', '..kNNk..', '...kk...',
  ),
  thit_bo: pixelSprite8(
    '........', '..kkkk..', '.krrrrk.', 'krrRrrrk', 'krrwwrrk', 'krrrrrrk', '.krrrrk.', '..kkkk..',
  ),
  thit_ga: pixelSprite8(
    '........', '..kcck..', '.kcccck.', 'kccwwcck', 'kcccccck', '.kcccck.', '..kttk..', '...kk...',
  ),
  uc_ga: pixelSprite8(
    '........', '..kkkk..', '.kccck..', 'kcccccck', 'kccwwcck', 'kcccccck', '.kcccck.', '..kkkk..',
  ),
  suon_heo: pixelSprite8(
    '........', '..kkkk..', '.krrrk..', 'krrrwrrk', 'krrrrrrk', '.krrrk..', '..krrk..', '...kk...',
  ),
  ca_thu_tuoi: pixelSprite8(
    '........', '..kkk...', '.ktttk..', 'kttwttk.', 'kttttttk', '.ktttk..', '..kkk...', '........',
  ),
  tom_tuoi: pixelSprite8(
    '........', '..krr...', '.krRrk..', 'krRRrrk.', '.krRrrk.', '..krRk..', '...kk...', '........',
  ),
  khoai_tay_chien: groceryBag8('Y', 'w', 'o'),
  ga_vien_dong_lanh: groceryBag8('c', 'o', 'r'),
  pizza_dong_lanh: groceryBag8('R', 'Y', 'r'),
  muc_khoanh_dong_lanh: groceryBag8('c', 's', 'L'),
  rau_cu_dong_lanh: groceryBag8('n', 'Y', 'L'),
  cha_ca_thac_lat: groceryBag8('w', 't', 'r'),
  yen_mach: groceryCarton8('t', 'Y', 'b'),
  ngu_coc: groceryCarton8('Y', 'r', 'o'),
  mat_ong: groceryJar8('Y', 'w', 'b'),
  bo_dau_phong: groceryJar8('t', 'Y', 'b'),
  tuong_ca: drinkBottle8('r', 'w', 'R'),
  sot_mayonnaise: drinkBottle8('w', 'Y', 's'),
  banh_pia: groceryBag8('t', 'Y', 'r'),
  keo_dua: groceryBag8('c', 'w', 't'),
  banh_mochi: groceryBag8('p', 'w', 'r'),
  hat_bi_rang: groceryBag8('n', 'Y', 'N'),
  dau_ha_lan_say: groceryBag8('n', 'w', 'Y'),
  khoai_tay_que: groceryBag8('Y', 'o', 't'),
  nuoc_rua_tay: drinkBottle8('l', 'w', 'L'),
  nuoc_lau_kinh: drinkBottle8('L', 'w', 'l'),
  nuoc_tay_bon_cau: drinkBottle8('l', 'N', 'L'),
  mang_boc_thuc_pham: groceryCarton8('s', 'w', 'L'),
  khan_uot: groceryBag8('l', 'w', 'L'),
  thuc_an_cho: groceryBag8('t', 'Y', 'b'),
  thuc_an_meo: groceryBag8('b', 'w', 't'),
} satisfies Record<string, Sprite>);

function groceryCarton8(body: string, label: string, top: string): Sprite {
  return drinkCarton8(body, label, top);
}
