import React,{useRef,useState} from 'react';
import {PixelDialog,PixelButton} from './pixel';
import {parseSaveFile,type SaveSummary} from '../save-file';
import type {SaveGameData} from '@game/shared';
interface Props {onManualSave:()=>Promise<boolean>;onResetSave:()=>Promise<boolean>;onExportSave:()=>Promise<boolean>;onImportSave:(save:SaveGameData)=>Promise<boolean>;isOnline?:boolean;onClose:()=>void;lastSavedAt?:string;revision?:number;}
const money=(value:number)=>`${value.toLocaleString('vi-VN')}₫`;
export const SaveModal:React.FC<Props>=({onManualSave,onResetSave,onExportSave,onImportSave,isOnline=false,onClose,lastSavedAt,revision=1})=>{
 const [confirm,setConfirm]=useState(false),[pending,setPending]=useState(false),[status,setStatus]=useState(''),[failed,setFailed]=useState(false);
 const [incoming,setIncoming]=useState<{save:SaveGameData;summary:SaveSummary;migratedFromSchema?:number}|null>(null);
 const fileInput=useRef<HTMLInputElement>(null);
 const perform=async(reset:boolean)=>{setPending(true);setStatus(reset?'Đang mở tiệm mới...':'Đang ghi lại tiến trình...');setFailed(false);try{const ok=await(reset?onResetSave():onManualSave());setFailed(!ok);setStatus(ok?(reset?'Tiệm mới đã sẵn sàng.':'Đã lưu tiến trình thành công.'):'Chưa lưu được. Hãy thử lại.');if(ok&&reset)setConfirm(false);}catch{setFailed(true);setStatus('Chưa lưu được. Hãy thử lại.');}finally{setPending(false);}};
 const exportFile=async()=>{setPending(true);setFailed(false);setStatus('Đang xuất file...');try{const ok=await onExportSave();setFailed(!ok);setStatus(ok?'Đã xuất bản lưu ra file.':'Chưa xuất được file.');}catch{setFailed(true);setStatus('Chưa xuất được file.');}finally{setPending(false);}};
 const chooseFile=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setIncoming(null);setFailed(false);setStatus('Đang đọc file...');try{const parsed=parseSaveFile(await file.text());if(!parsed.ok){setFailed(true);setStatus(parsed.error);return;}setIncoming(parsed);setStatus('');}catch{setFailed(true);setStatus('Không đọc được file.');}};
 const applyImport=async()=>{if(!incoming)return;setPending(true);setFailed(false);setStatus('Đang nhập bản lưu...');try{const ok=await onImportSave(incoming.save);setFailed(!ok);setStatus(ok?'Đã nhập bản lưu. Bản cũ được giữ làm dự phòng.':'Chưa nhập được bản lưu.');if(ok)setIncoming(null);}catch{setFailed(true);setStatus('Chưa nhập được bản lưu.');}finally{setPending(false);}};
 return <PixelDialog title="Giữ lại chuyện của tiệm" subtitle="Tiến trình được lưu trên trình duyệt này" icon="save" onClose={onClose}>
  <div className="info-card"><div className="section-label"><span>Lần lưu thành công gần nhất</span><strong>{lastSavedAt?new Date(lastSavedAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'Chưa có'}</strong></div><div className="section-label"><span>Lần ghi tiến trình</span><strong>#{revision}</strong></div></div>
  <div className="info-card"><p>Tiệm tự lưu mỗi 30 giây và khi qua ngày mới. Bạn cũng có thể lưu trước khi rời tiệm.</p><p className="muted">Tiến trình nằm trên máy này. Xóa dữ liệu trình duyệt có thể làm mất bản lưu. Hãy xuất ra file để giữ một bản dự phòng ngoài trình duyệt.</p></div>
  <div className="save-actions"><PixelButton icon="save" variant="teal" disabled={pending} onClick={()=>perform(false)}>Lưu tiến trình ngay</PixelButton><PixelButton disabled={pending||isOnline} onClick={exportFile}>Xuất bản lưu ra file</PixelButton><PixelButton disabled={pending||isOnline} onClick={()=>fileInput.current?.click()}>Nhập bản lưu từ file</PixelButton><PixelButton disabled={pending} onClick={()=>setConfirm(true)}>Mở tiệm mới từ đầu</PixelButton></div>
  <input ref={fileInput} type="file" accept="application/json,.json" hidden onChange={chooseFile} aria-label="Chọn file bản lưu"/>
  {isOnline&&<p className="muted">Tiệm online nằm trên máy chủ nên không xuất/nhập file được.</p>}
  {status&&<p role="status" className={`save-status ${failed?'error':''}`}>{status}</p>}
  {incoming&&<div className="save-confirm"><p><strong>Thay bản lưu hiện tại bằng file này?</strong> Ngày {incoming.summary.day} · cấp {incoming.summary.level} · {money(incoming.summary.money)} · doanh thu {money(incoming.summary.totalRevenue)}. Bản lưu hiện tại được giữ làm bản dự phòng (chỉ một bản, lần nhập sau sẽ ghi đè).{incoming.migratedFromSchema?` File thuộc phiên bản cũ (${incoming.migratedFromSchema}) và sẽ được nâng cấp.`:''}</p><div><PixelButton variant="brick" disabled={pending} onClick={applyImport}>Đồng ý nhập</PixelButton><PixelButton disabled={pending} onClick={()=>setIncoming(null)}>Giữ lại tiệm</PixelButton></div></div>}
  {confirm&&<div className="save-confirm"><p><strong>Chơi lại từ ngày 1?</strong> Tiền và hàng của bản lưu hiện tại sẽ được thay bằng tiệm mới.</p><div><PixelButton variant="brick" disabled={pending} onClick={()=>perform(true)}>Đồng ý chơi lại</PixelButton><PixelButton disabled={pending} onClick={()=>setConfirm(false)}>Giữ lại tiệm</PixelButton></div></div>}
 </PixelDialog>;
};
