export * from './products';
export * from './fridge';
export * from './recipes';
export * from './buildings';
// Mô hình thế giới mở (OpenSpec `open-world-land-grid`): tên trùng (BuildingBounds, BuildingId, *_PLOT_ID…) đã re-export qua `./buildings`.
export * from './world/world-grid';
export * from './world/parcels';
export * from './world/waves';
export * from './world/infrastructure';
export {
  DEFAULT_PLACEMENTS, DEFAULT_GEOMETRY, placementGeometry, mainEastWingTiles, validatePlacements, normalizePlacements, placementsProblem, placementTop, placementEastWall, placementFloor, footprintBlockers, mainBlockedRects, warehouseGeometry, resolvePlacements, validatePlacement, layoutBuildings, defaultPlacementOf, placedBuildingIds, type BuildingInfo, type BuildingPlacement, type PlacementGeometry,
} from './world/placements';
export { adjacentParcels } from './world/parcels';
export * from './world/footprint';
export { BUILDING_TEMPLATES, MAIN_EAST_WING_PLOT_IDS, MAIN_EAST_WING_COLUMNS, type BuildingTemplate, type RelTile } from './world/building-templates';
export * from './map';
export * from './traffic';
export * from './arrival-modes';
export * from './maintenance';
export * from './reviews';
export * from './security';
export * from './land';
export * from './pixel-art';
export * from './pixel-art-cold';
export * from './online-world';
export * from './catalog-manifest';
export * from './catalog.test';
export * from './suppliers';
export * from './staff';
export * from './seasons';
export * from './stalls';
export * from './weather';
export * from './product-tags';
export * from './market-events';
export * from './modifiers';
export * from './pricing';
export * from './supplier-market';
export * from './spoilage';
export * from './forecast';
export * from './progression';
export * from './regulars';
export * from './partyOrders';
export * from './goals';
export * from './dining';
export * from './story';
export * from './skills';
export * from './titles';
export * from './decor';
export * from './logistics';
export * from './store-types';
export * from './weather-visual';
export * from './shelter';
export * from './weather-sprite-layout';
export * from './neighborhood';
export * from './neighborhood-collision';
export * from './neighborhood-dialogue';
