import { Product, ProductCategory, StorageType } from '@game/shared';

export const STARTER_PRODUCTS: Product[] = [
  {
    id: 'mi_hao_hao',
    name: 'Mì Tôm Hảo Hảo',
    category: 'instant_noodles',
    spriteId: 'item_mi_hao_hao',
    purchasePrice: 3000,
    baseSellingPrice: 4500,
    shelfCapacity: 24,
    storageType: 'ambient',
    expirationRules: {
      daysToSpoil: 90,
    },
    unlockLevel: 1,
    demandProfile: {
      basePopularity: 0.95,
    },
    description: 'Mì tôm chua cay huyền thoại tuổi thơ. Hàng bán chạy nhất xóm, già trẻ lớn bé ai cũng thích.',
  },
  {
    id: 'xa_xi_chuong_duong',
    name: 'Xá Xị Chương Dương',
    category: 'soft_drinks',
    spriteId: 'item_xa_xi',
    purchasePrice: 5000,
    baseSellingPrice: 8000,
    shelfCapacity: 16,
    storageType: 'ambient',
    expirationRules: {
      daysToSpoil: 60,
    },
    unlockLevel: 1,
    demandProfile: {
      basePopularity: 0.8,
    },
    description: 'Chai xá xị thủy tinh ướp lạnh, thơm lừng vị thảo mộc sảng khoái trưa hè oi ả.',
  },
  {
    id: 'keo_big_babol',
    name: 'Kẹo Cao Su Big Babol',
    category: 'candy',
    spriteId: 'item_keo_big_babol',
    purchasePrice: 1000,
    baseSellingPrice: 2000,
    shelfCapacity: 30,
    storageType: 'ambient',
    expirationRules: {
      daysToSpoil: 180,
    },
    unlockLevel: 1,
    demandProfile: {
      basePopularity: 0.9,
    },
    description: 'Kẹo thổi bong bóng vị dưa hấu quen thuộc của học trò tiểu học sau giờ tan trường.',
  },
  {
    id: 'sua_ong_tho',
    name: 'Sữa Đặc Ông Thọ Đỏ',
    category: 'milk',
    spriteId: 'item_sua_ong_tho',
    purchasePrice: 18000,
    baseSellingPrice: 24000,
    shelfCapacity: 12,
    storageType: 'ambient',
    expirationRules: {
      daysToSpoil: 120,
    },
    unlockLevel: 1,
    demandProfile: {
      basePopularity: 0.75,
    },
    description: 'Hộp sữa đặc có đường nắp giật, không thể thiếu cho ly cà phê sữa đá buổi sáng.',
  },
  {
    id: 'banh_mi_que',
    name: 'Bánh Mì Que Giòn Cay',
    category: 'bread',
    spriteId: 'item_banh_mi_que',
    purchasePrice: 6000,
    baseSellingPrice: 10000,
    shelfCapacity: 10,
    storageType: 'ambient',
    expirationRules: {
      daysToSpoil: 2,
    },
    unlockLevel: 1,
    demandProfile: {
      basePopularity: 0.85,
    },
    description: 'Bánh mì que kẹp patê béo ngậy quết chí chương cay xé lưỡi, ăn là ghiền.',
  },
];

type CatalogRow = [string, string, ProductCategory, number, number, number, StorageType, number, number];

// id, Vietnamese name, category, purchase/sale price, shelf capacity, storage,
// shelf life in game days, unlock level. Keep catalog data out of the renderer.
const ADDITIONAL_ROWS: CatalogRow[] = [
  ['mi_omachi', 'Mì Omachi khoai tây', 'instant_noodles', 5000, 7500, 20, 'ambient', 90, 1],
  ['mi_ba_mien', 'Mì Ba Miền bò hầm', 'instant_noodles', 3200, 5000, 24, 'ambient', 90, 1],
  ['pho_goi', 'Phở gói Hà Nội', 'instant_noodles', 5500, 8000, 18, 'ambient', 75, 2],
  ['hu_tieu_goi', 'Hủ tiếu Nam Vang gói', 'instant_noodles', 6000, 9000, 18, 'ambient', 75, 2],
  ['banh_poca', 'Khoai tây chiên Poca', 'snacks', 7000, 10000, 18, 'ambient', 60, 1],
  ['bim_bim_oishi', 'Snack Oishi tôm cay', 'snacks', 4000, 6500, 20, 'ambient', 60, 1],
  ['banh_gao', 'Bánh gạo vị ngọt', 'snacks', 9000, 13000, 16, 'ambient', 50, 2],
  ['dau_phong_rang', 'Đậu phộng rang tỏi', 'snacks', 8000, 12000, 16, 'ambient', 25, 2],
  ['keo_dua', 'Kẹo dừa Bến Tre', 'candy', 2500, 4000, 24, 'ambient', 90, 1],
  ['keo_me', 'Kẹo mè xửng Huế', 'candy', 3500, 5500, 20, 'ambient', 90, 2],
  ['socola_thanh', 'Sô cô la thanh', 'candy', 9000, 14000, 16, 'ambient', 60, 2],
  ['nuoc_suoi', 'Nước suối chai nhỏ', 'bottled_water', 3000, 5000, 24, 'ambient', 180, 1],
  ['nuoc_khoang', 'Nước khoáng Vĩnh Hảo', 'bottled_water', 5000, 7500, 20, 'ambient', 180, 2],
  ['nuoc_tinh_khiet', 'Nước tinh khiết bình nhỏ', 'bottled_water', 4500, 7000, 20, 'ambient', 180, 1],
  ['nuoc_cam', 'Nước cam có ga', 'soft_drinks', 6000, 9000, 16, 'ambient', 90, 1],
  ['tra_xanh', 'Trà xanh đóng chai', 'soft_drinks', 6500, 10000, 16, 'ambient', 60, 2],
  ['sua_tuoi', 'Sữa tươi hộp', 'milk', 8500, 12000, 12, 'cold', 7, 1],
  ['sua_chua', 'Sữa chua hũ', 'milk', 5000, 8000, 12, 'cold', 5, 1],
  ['sua_dau_nanh', 'Sữa đậu nành chai', 'milk', 6000, 9000, 12, 'cold', 4, 2],
  ['banh_mi_goi', 'Bánh mì gối lát', 'bread', 14000, 20000, 10, 'ambient', 5, 1],
  ['banh_bao', 'Bánh bao nhân thịt', 'bread', 10000, 15000, 10, 'cold', 3, 2],
  ['trung_ga', 'Trứng gà', 'eggs', 2800, 4500, 20, 'cold', 12, 1],
  ['trung_vit', 'Trứng vịt', 'eggs', 3500, 5500, 20, 'cold', 12, 2],
  ['nuoc_mam', 'Nước mắm chai nhỏ', 'cooking_ingredients', 16000, 23000, 12, 'ambient', 180, 1],
  ['duong_cat', 'Đường cát trắng', 'cooking_ingredients', 12000, 18000, 12, 'ambient', 180, 1],
  ['bot_ngot', 'Bột ngọt gói nhỏ', 'cooking_ingredients', 9000, 14000, 14, 'ambient', 180, 2],
  ['dau_an', 'Dầu ăn chai nhỏ', 'cooking_ingredients', 26000, 36000, 10, 'ambient', 120, 2],
  ['xa_phong', 'Xà phòng cục', 'household', 7000, 11000, 16, 'ambient', 365, 1],
  ['nuoc_rua_chen', 'Nước rửa chén túi', 'household', 13000, 19000, 12, 'ambient', 365, 2],
  ['giay_ve_sinh', 'Giấy vệ sinh cuộn', 'household', 8000, 12000, 16, 'ambient', 365, 1],
  ['kem_danh_rang', 'Kem đánh răng tuýp', 'household', 17000, 25000, 12, 'ambient', 365, 2],
];

export const ADDITIONAL_PRODUCTS: Product[] = ADDITIONAL_ROWS.map(([
  id, name, category, purchasePrice, baseSellingPrice, shelfCapacity, storageType, daysToSpoil, unlockLevel,
]) => ({
  id, name, category, purchasePrice, baseSellingPrice, shelfCapacity, storageType, unlockLevel,
  spriteId: `item_${id}`,
  expirationRules: { daysToSpoil },
  demandProfile: { basePopularity: 0.6 },
  description: `${name} quen thuộc ở tiệm tạp hóa đầu hẻm.`,
}));

export const CURATED_PRODUCTS: Product[] = [
  {
    id: 'nuoc_rua_tay',
    name: 'Nước Rửa Tay Diệt Khuẩn',
    category: 'household',
    spriteId: 'item_nuoc_rua_tay',
    purchasePrice: 18000,
    baseSellingPrice: 26000,
    shelfCapacity: 12,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 365 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.65 },
    description: 'Chai nước rửa tay sạch khuẩn hương táo dịu nhẹ, giữ đôi tay luôn thơm tho sạch sẽ.',
  },
  {
    id: 'nuoc_lau_kinh',
    name: 'Nước Lau Kính Sáng Bóng',
    category: 'household',
    spriteId: 'item_nuoc_lau_kinh',
    purchasePrice: 15000,
    baseSellingPrice: 22000,
    shelfCapacity: 12,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 365 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.55 },
    description: 'Bình xịt lau kính gương sạch bóng không để lại vệt mờ hay bụi bẩn.',
  },
  {
    id: 'nuoc_tay_bon_cau',
    name: 'Nước Tẩy Bồn Cầu Đậm Đặc',
    category: 'household',
    spriteId: 'item_nuoc_tay_bon_cau',
    purchasePrice: 22000,
    baseSellingPrice: 32000,
    shelfCapacity: 10,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 365 },
    unlockLevel: 3,
    demandProfile: { basePopularity: 0.6 },
    description: 'Dung dịch tẩy rửa vệ sinh diệt khuẩn cực mạnh, đánh bay vết ố vàng cứng đầu.',
  },
  {
    id: 'mang_boc_thuc_pham',
    name: 'Màng Bọc Thực Phẩm PE',
    category: 'household',
    spriteId: 'item_mang_boc_thuc_pham',
    purchasePrice: 14000,
    baseSellingPrice: 20000,
    shelfCapacity: 16,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 365 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.7 },
    description: 'Cuộn màng bọc bảo quản thực phẩm tươi ngon, ngăn mùi tủ lạnh hiệu quả.',
  },
  {
    id: 'khan_uot',
    name: 'Khăn Ướt Tiệt Trùng Em Bé',
    category: 'household',
    spriteId: 'item_khan_uot',
    purchasePrice: 9000,
    baseSellingPrice: 14000,
    shelfCapacity: 18,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 180 },
    unlockLevel: 1,
    demandProfile: { basePopularity: 0.8 },
    description: 'Gói khăn ướt dịu nhẹ không cồn, tiện lợi cho mọi nhu cầu vệ sinh hằng ngày.',
  },
  {
    id: 'thuc_an_cho',
    name: 'Thức Ăn Hạt Cho Chó',
    category: 'household',
    spriteId: 'item_thuc_an_cho',
    purchasePrice: 25000,
    baseSellingPrice: 36000,
    shelfCapacity: 12,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 180 },
    unlockLevel: 3,
    demandProfile: { basePopularity: 0.6 },
    description: 'Túi hạt thơm ngon bổ sung canxi và dưỡng chất cho cún cưng khỏe mạnh.',
  },
  {
    id: 'thuc_an_meo',
    name: 'Thức Ăn Hạt Cho Mèo',
    category: 'household',
    spriteId: 'item_thuc_an_meo',
    purchasePrice: 24000,
    baseSellingPrice: 35000,
    shelfCapacity: 12,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 180 },
    unlockLevel: 3,
    demandProfile: { basePopularity: 0.65 },
    description: 'Hạt dinh dưỡng vị cá ngừ thơm lừng yêu thích của các chú mèo đầu hẻm.',
  },
  {
    id: 'sot_mayonnaise',
    name: 'Sốt Mayonnaise Béo Ngậy',
    category: 'cooking_ingredients',
    spriteId: 'item_sot_mayonnaise',
    purchasePrice: 19000,
    baseSellingPrice: 27000,
    shelfCapacity: 12,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 90 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.7 },
    description: 'Chai xốt mayonnaise sánh mịn, béo ngậy chấm bánh mì hay trộn salad rau củ.',
  },
  {
    id: 'ca_moi_hop',
    name: 'Cá Mòi Xốt Cà Đóng Hộp',
    category: 'cooking_ingredients',
    spriteId: 'item_ca_moi_hop',
    purchasePrice: 16000,
    baseSellingPrice: 23000,
    shelfCapacity: 14,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 180 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.75 },
    description: 'Hộp cá mòi sốt cà đậm vị chua ngọt, món ăn kèm bánh mì nóng giòn kinh điển.',
  },
  {
    id: 'bot_ca_cao',
    name: 'Bột Ca Cao Nguyên Chất',
    category: 'cooking_ingredients',
    spriteId: 'item_bot_ca_cao',
    purchasePrice: 28000,
    baseSellingPrice: 40000,
    shelfCapacity: 12,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 180 },
    unlockLevel: 3,
    demandProfile: { basePopularity: 0.6 },
    description: 'Hũ bột ca cao thơm lừng, dùng pha thức uống nóng ấm hoặc làm bánh ngọt.',
  },
  {
    id: 'bot_ca_ri',
    name: 'Bột Cà Ri Ấn Độ',
    category: 'cooking_ingredients',
    spriteId: 'item_bot_ca_ri',
    purchasePrice: 8000,
    baseSellingPrice: 12000,
    shelfCapacity: 20,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 180 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.65 },
    description: 'Gia vị thảo mộc nấu món cà ri gà béo ngậy chấm bánh mì thơm nức xóm nhỏ.',
  },
  {
    id: 'ngu_vi_huong',
    name: 'Bột Ngũ Vị Hương Gia Vị',
    category: 'cooking_ingredients',
    spriteId: 'item_ngu_vi_huong',
    purchasePrice: 5000,
    baseSellingPrice: 8000,
    shelfCapacity: 24,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 180 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.7 },
    description: 'Gói gia vị tẩm ướp thịt nướng, phá lấu đậm đà hương vị truyền thống.',
  },
  {
    id: 'sa_te_tom',
    name: 'Sa Tế Tôm Cay Nồng',
    category: 'cooking_ingredients',
    spriteId: 'item_sa_te_tom',
    purchasePrice: 11000,
    baseSellingPrice: 16000,
    shelfCapacity: 16,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 120 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.75 },
    description: 'Hũ sa tế tôm cay xé lưỡi, ăn cùng bún bò, hủ tiếu hay lẩu ấm bụng ngày mưa.',
  },
  {
    id: 'dau_do',
    name: 'Đậu Đỏ Hạt Đóng Gói',
    category: 'cooking_ingredients',
    spriteId: 'item_dau_do',
    purchasePrice: 13000,
    baseSellingPrice: 19000,
    shelfCapacity: 16,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 180 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.65 },
    description: 'Bịch đậu đỏ hạt mẩy bở tơi, chuyên dùng nấu chè đậu đỏ ngọt mát cầu may mắn.',
  },
  {
    id: 'banh_pia',
    name: 'Bánh Pía Sóc Trăng Sầu Riêng',
    category: 'snacks',
    spriteId: 'item_banh_pia',
    purchasePrice: 22000,
    baseSellingPrice: 32000,
    shelfCapacity: 12,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 30 },
    unlockLevel: 3,
    demandProfile: { basePopularity: 0.8 },
    description: 'Đặc sản vỏ ngàn lớp nhân đậu xanh sầu riêng trứng muối thơm nức bùi béo.',
  },
  {
    id: 'kho_ga',
    name: 'Khô Gà Lá Chanh Cay Cay',
    category: 'snacks',
    spriteId: 'item_kho_ga',
    purchasePrice: 24000,
    baseSellingPrice: 35000,
    shelfCapacity: 14,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 45 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.85 },
    description: 'Khô gà xé sợi vàng ruộm giòn dai, thơm nồng mùi lá chanh và ớt hiểm cay cay.',
  },
  {
    id: 'banh_mochi',
    name: 'Bánh Mochi Dẻo Mềm Nhân Kem',
    category: 'snacks',
    spriteId: 'item_banh_mochi',
    purchasePrice: 16000,
    baseSellingPrice: 24000,
    shelfCapacity: 14,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 25 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.7 },
    description: 'Bánh gạo dẻo phong cách Nhật Bản mát mềm ngọt dịu, cắn ngập nhân kem.',
  },
  {
    id: 'hat_bi_rang',
    name: 'Hạt Bí Rang Củi Ngày Tết',
    category: 'snacks',
    spriteId: 'item_hat_bi_rang',
    purchasePrice: 15000,
    baseSellingPrice: 22000,
    shelfCapacity: 16,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 90 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.75 },
    description: 'Hạt bí nếp rang củi thơm giòn béo ngậy, món nhâm nhi chuyện trò rôm rả.',
  },
  {
    id: 'dau_ha_lan_say',
    name: 'Đậu Hà Lan Sấy Giòn Vị Tỏi Ớt',
    category: 'snacks',
    spriteId: 'item_dau_ha_lan_say',
    purchasePrice: 12000,
    baseSellingPrice: 18000,
    shelfCapacity: 16,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 60 },
    unlockLevel: 2,
    demandProfile: { basePopularity: 0.7 },
    description: 'Hạt đậu Hà Lan xanh giòn rụm vị tỏi ớt mặn ngọt, ăn hoài không ngán.',
  },
  {
    id: 'khoai_tay_que',
    name: 'Khoai Tây Cọng Que Giòn Rụm',
    category: 'snacks',
    spriteId: 'item_khoai_tay_que',
    purchasePrice: 10000,
    baseSellingPrice: 15000,
    shelfCapacity: 18,
    storageType: 'ambient',
    expirationRules: { daysToSpoil: 60 },
    unlockLevel: 1,
    demandProfile: { basePopularity: 0.8 },
    description: 'Khoai tây cắt que tẩm muối giòn rụm, món khoái khẩu của các bạn nhỏ trong hẻm.',
  },
];

/** Sản phẩm theo mùa/thời tiết (kem, đồ che mưa, đồ uống nóng, hàng tươi). Không biến mất khi hết mùa: nhu cầu đổi qua bộ chỉnh. */
export const SEASONAL_PRODUCTS: Product[] = [
  { id: 'kem_que', name: 'Kem que sữa dừa', category: 'snacks', spriteId: 'item_kem_que', purchasePrice: 6000, baseSellingPrice: 10000, shelfCapacity: 14, storageType: 'cold', expirationRules: { daysToSpoil: 20 }, unlockLevel: 2, demandProfile: { basePopularity: 0.55 }, description: 'Que kem sữa dừa mát lạnh, ngày nắng nóng ai đi ngang cũng ghé mua một cây.' },
  { id: 'o_gap', name: 'Ô gấp che mưa', category: 'household', spriteId: 'item_o_gap', purchasePrice: 45000, baseSellingPrice: 65000, shelfCapacity: 10, storageType: 'ambient', unlockLevel: 2, demandProfile: { basePopularity: 0.3 }, description: 'Chiếc ô gấp gọn cho cơn mưa chiều bất chợt, bán chạy nhất khi trời đổ mưa.' },
  { id: 'ao_mua_bo', name: 'Áo mưa bộ người lớn', category: 'household', spriteId: 'item_ao_mua_bo', purchasePrice: 30000, baseSellingPrice: 45000, shelfCapacity: 12, storageType: 'ambient', unlockLevel: 1, demandProfile: { basePopularity: 0.35 }, description: 'Áo mưa hai mảnh cho dân chạy xe máy; mưa xuống là hết sạch.' },
  { id: 'ca_phe_hoa_tan', name: 'Cà phê sữa hòa tan (bịch 10 gói)', category: 'soft_drinks', spriteId: 'item_ca_phe_hoa_tan', purchasePrice: 38000, baseSellingPrice: 52000, shelfCapacity: 12, storageType: 'ambient', expirationRules: { daysToSpoil: 240 }, unlockLevel: 1, demandProfile: { basePopularity: 0.5 }, description: 'Cà phê sữa pha nóng buổi sáng, thêm ấm áp những ngày mưa và se lạnh.' },
  { id: 'tra_nong_gung', name: 'Trà gừng hòa tan', category: 'soft_drinks', spriteId: 'item_tra_nong_gung', purchasePrice: 25000, baseSellingPrice: 36000, shelfCapacity: 12, storageType: 'ambient', expirationRules: { daysToSpoil: 240 }, unlockLevel: 2, demandProfile: { basePopularity: 0.4 }, description: 'Trà gừng pha nóng cho ngày lạnh, ấm bụng dễ ngủ.' },
  { id: 'thit_heo_tuoi', name: 'Thịt heo tươi 300g', category: 'cooking_ingredients', spriteId: 'item_thit_heo_tuoi', purchasePrice: 38000, baseSellingPrice: 52000, shelfCapacity: 10, storageType: 'cold', expirationRules: { daysToSpoil: 2 }, unlockLevel: 3, demandProfile: { basePopularity: 0.45 }, description: 'Thịt heo ba rọi tươi trong ngày, sắm Tết và nấu bữa cơm chiều.' },
  { id: 'rau_cai_xanh', name: 'Rau cải xanh (bó)', category: 'cooking_ingredients', spriteId: 'item_rau_cai_xanh', purchasePrice: 6000, baseSellingPrice: 10000, shelfCapacity: 14, storageType: 'cold', expirationRules: { daysToSpoil: 3 }, unlockLevel: 2, demandProfile: { basePopularity: 0.5 }, description: 'Bó cải xanh tươi, để lâu là héo nên phải bán cho nhanh.' },
];

export const ALL_PRODUCTS: Product[] = [
  ...STARTER_PRODUCTS,
  ...ADDITIONAL_PRODUCTS,
  ...CURATED_PRODUCTS,
  ...SEASONAL_PRODUCTS,
];

export const PRODUCT_CATEGORY_LABELS: Record<ProductCategory, string> = {
  instant_noodles: 'Mì ăn liền', snacks: 'Bánh ăn vặt', candy: 'Kẹo', bottled_water: 'Nước suối',
  soft_drinks: 'Nước ngọt', milk: 'Sữa', bread: 'Bánh mì', eggs: 'Trứng',
  cooking_ingredients: 'Gia vị', household: 'Đồ gia dụng',
};

export const PRODUCT_MAP: Record<string, Product> = ALL_PRODUCTS.reduce(
  (acc, prod) => {
    acc[prod.id] = prod;
    return acc;
  },
  {} as Record<string, Product>
);
