// Đo hiệu năng render (không chạy tự động, chỉ dev): dán/eval khi game đang chạy ở `yarn dev` (cần window.__viewport, __sim, setDebugTime).
// Số đo là CHIỀU HƯỚNG: chạy trong emulator/WebGL phần mềm, không phải GPU thiết bị thật; rAF của pane bị hạn tốc khi không hiển thị
// (gọi screenshot ngay trước mỗi lần đo). Dùng __renderCost/__tickCost (ms CPU+đồng bộ GL) thay vì FPS khi so sánh kịch bản.
//   await __trio('640x360')            idle / mưa to / đêm+mưa to: tick (JS) và render (đồng bộ gl.finish) trung bình + p95
//   await __perf(4000)                 FPS/khoảng khung thực tế, DPR, kích thước canvas
//   __count()                          số node/sprite/graphics trong stage
//   __freeze(true|false)               tắt/bật adaptResolution khi đo (đừng để DPR tự hạ giữa chừng)
const v = () => window.__viewport;
window.__freeze = (on) => { const x = v(); if (on) { x.adaptResolution = () => {}; x.qualityCap = 2; x.frameEma = 16; x.slowFrames = 0; x.updateResponsiveSettings(); } else delete x.adaptResolution; };
window.__perf = (ms = 4000) => new Promise((res) => { const app = v().app; const ts = []; let last = performance.now(); const f = () => { const n = performance.now(); ts.push(n - last); last = n; }; app.ticker.add(f); setTimeout(() => { app.ticker.remove(f); const s = [...ts].sort((a, b) => a - b); const avg = ts.reduce((a, b) => a + b, 0) / ts.length; const c = document.querySelector('canvas'); res({ n: ts.length, fps: +(1000 / avg).toFixed(1), avgMs: +avg.toFixed(1), p95: +s[Math.floor(s.length * 0.95)].toFixed(1), max: +s[s.length - 1].toFixed(1), dpr: app.renderer.resolution, cap: v().qualityCap, canvas: c.width + 'x' + c.height, vp: innerWidth + 'x' + innerHeight }); }, ms); });
window.__renderCost = (ms = 3000) => new Promise((res) => { const r = v().app.renderer; const orig = r.render.bind(r); const gl = r.gl; const t = []; r.render = function (...a) { const t0 = performance.now(); const out = orig(...a); if (gl && gl.finish) gl.finish(); t.push(performance.now() - t0); return out; }; setTimeout(() => { r.render = orig; const s = [...t].sort((a, b) => a - b); res({ n: t.length, avg: +(t.reduce((a, b) => a + b, 0) / t.length).toFixed(1), p95: +s[Math.floor(s.length * 0.95)].toFixed(1), max: +s[s.length - 1].toFixed(1) }); }, ms); });
window.__tickCost = (ms = 3000) => new Promise((res) => { const x = v(); const orig = x.renderTick; const t = []; const w = function (...a) { const t0 = performance.now(); orig.apply(x, a); t.push(performance.now() - t0); }; x.app.ticker.remove(orig); x.app.ticker.add(w); setTimeout(() => { x.app.ticker.remove(w); x.app.ticker.add(orig); const s = [...t].sort((a, b) => a - b); res({ n: t.length, avg: +(t.reduce((a, b) => a + b, 0) / t.length).toFixed(2), p95: +s[Math.floor(s.length * 0.95)].toFixed(2), max: +s[s.length - 1].toFixed(2) }); }, ms); });
window.__count = () => { let n = 0, vis = 0, sprites = 0, gfx = 0; const walk = (o, pv) => { n++; const ok = pv && o.visible !== false && o.alpha !== 0 && o.renderable !== false; if (ok) vis++; const k = o.constructor.name; if (k === 'Sprite' || k === 'AnimatedSprite') sprites++; else if (k === 'Graphics') gfx++; for (const c of o.children || []) walk(c, ok); }; walk(v().app.stage, true); return { nodes: n, visible: vis, sprites, gfx }; };
window.__s3 = async (label, o = {}) => { if (document.documentElement.dataset.dialogs) return 'DIALOG OPEN'; __freeze(true); setDebugTime(window.__sim.getTime().day, o.hour ?? 12, 0, o.rain ?? 0); v().weatherModel.transitionWeather(o.weather ?? 'clear', 50); await new Promise((r) => setTimeout(r, 900)); const a = await __tickCost(2500); const b = await __renderCost(2500); return JSON.stringify({ label, tickMs: a.avg, tickP95: a.p95, renderMs: b.avg, renderP95: b.p95 }); };
window.__trio = async (tag) => { const o = []; for (const [l, x] of [['idle', { hour: 12 }], ['heavy rain', { hour: 12, weather: 'rain_heavy', rain: 1 }], ['night+heavy rain', { hour: 22, weather: 'rain_heavy', rain: 1 }]]) o.push(JSON.parse(await __s3(`${tag} ${l}`, x))); return JSON.stringify({ vp: innerWidth + 'x' + innerHeight, dpr: v().app.renderer.resolution, nodes: __count().nodes, rows: o.map((r) => `${r.label}: tick ${r.tickMs} / render ${r.renderMs} (p95 ${r.renderP95})`) }); };
